"""
vless_installer/modules/trusttunnel.py
───────────────────────────────────────────────────────────────────────────────
TrustTunnel protocol module — integration layer for the upstream TrustTunnel
endpoint binary (https://github.com/TrustTunnel/TrustTunnel).

ARCHITECTURE
============
This module wraps the upstream prebuilt Rust binary (`trusttunnel_endpoint` +
`setup_wizard`) and exposes a project-native API matching the patterns used by
fptn.py, hysteria2.py, mieru.py, etc.

KEY DESIGN DECISIONS (from Phase 0 report, decisions D1–D10):
  • D1  Certs: use project's existing ssl_certbot.obtain_ssl_cert() + certbot
        renewal cron, NOT setup_wizard's built-in ACME (which is one-shot, no
        auto-renewal). Feed via --cert-type provided.
  • D2  Port: default 8443 (TCP+UDP), NOT 443 (443 is taken by VLESS TCP +
        Hysteria2 UDP). Conflict-checked via core.check_port_used_by_other_protocol.
  • D3  Credentials: edit credentials.toml + systemctl restart trusttunnel.
        NO hot-reload in upstream (SIGHUP only reloads hosts.toml).
        Batching is handled in user_lifecycle.py via batch_context().
  • D4  Client onboarding: tt://?<base64url-TLV> deep-link URI (upstream
        default format since v1.0.1). NOT the incompatible tt://user:pass@host
        format from HYDRA-ULTIMATE.
  • D5  Traffic accounting: aggregate-only via Prometheus /metrics endpoint.
        Upstream has NO per-user label. Recorded under synthetic "_aggregate"
        user_id. Documented limitation.
  • D6  Prebuilt upstream binaries (GPG-verified via AdGuard key
        28645AC9776EC4C00BCE2AFC0FE641E7235E2EC6). No cargo build.
  • D7  Domain must NOT collide with VLESS/NaiveProxy/FPTN/MTProto domains.
  • D8  Per-user passwords: deterministic SHA-256("trusttunnel-pass|" + uuid).
        Username = email (verbatim, NOT email.split('@')[0] — TrustTunnel
        allows arbitrary strings and email is the canonical project ID).
  • D9  systemd unit based on upstream template + ExecReload=/bin/kill -HUP
        $MAINPID (for cert renewal via SIGHUP without restart).
  • D10 File layout: this module + trusttunnel_packages.py + trusttunnel_mirrors.py
        + trusttunnel_health.py + trusttunnel_stats.py. Strictly additive.

STATE FILE
==========
/var/lib/xray-installer/trusttunnel.json:
  {
    "installed":       true,
    "version":         "1.0.33",
    "domain":          "tt.example.com",
    "listen_address":  "0.0.0.0:8443",
    "listen_port":     8443,
    "cert_type":       "provided",          # always "provided" (D1)
    "cert_chain_path": "/etc/letsencrypt/live/tt.example.com/fullchain.pem",
    "cert_key_path":   "/etc/letsencrypt/live/tt.example.com/privkey.pem",
    "install_dir":     "/opt/trusttunnel",
    "binary_path":     "/opt/trusttunnel/trusttunnel_endpoint",
    "wizard_path":     "/opt/trusttunnel/setup_wizard",
    "vpn_toml":        "/opt/trusttunnel/vpn.toml",
    "hosts_toml":      "/opt/trusttunnel/hosts.toml",
    "creds_toml":      "/opt/trusttunnel/credentials.toml",
    "rules_toml":      "/opt/trusttunnel/rules.toml",
    "metrics_port":    1987,
    "installed_at":    "2026-07-14T10:00:00Z"
  }

CREDENTIALS FILE (managed by this module, NOT by setup_wizard after initial install)
===================================================================================
/opt/trusttunnel/credentials.toml — TOML array of [[client]] tables:
  [[client]]
  username = "alice@example.com"
  password = "<64-char hex SHA-256 of uuid>"

  [[client]]
  username = "bob@example.com"
  password = "<64-char hex>"
  max_http2_conns = 16    # optional

This module reads/writes this file directly (no CLI subcommand exists in
upstream for user management — confirmed in Phase 0). After any edit, the
trusttunnel service must be restarted (SIGHUP does NOT reload credentials).

DEEP-LINK FORMAT (upstream tt://?<base64url-TLV>)
=================================================
The deep-link is generated by shelling out to:
  trusttunnel_endpoint vpn.toml hosts.toml -c <username> -a <address> [--format deeplink]

We also provide a pure-Python TLV+base64url codec (trusttunnel_deeplink_encode /
trusttunnel_deeplink_decode) so linkqr_lib.py can build URIs without spawning
the 17 MB binary on every /config or /qr request from the Telegram bot.

PUBLIC API (called by user_lifecycle.TrustTunnelAdapter)
=========================================================
  trusttunnel_load_state() -> dict
  trusttunnel_save_state(state) -> None
  trusttunnel_is_installed() -> bool

  # credentials.toml CRUD (atomic writes, idempotent)
  trusttunnel_list_users() -> list[dict]      # [{"username","password",...}, ...]
  trusttunnel_user_exists(username) -> bool
  trusttunnel_add_user(username, password, max_http2_conns=None, max_http3_conns=None) -> bool
  trusttunnel_remove_user(username) -> bool
  trusttunnel_update_user(username, **fields) -> bool

  # deep-link generation
  trusttunnel_generate_deeplink(username, address=None) -> str   # shells out to endpoint
  trusttunnel_deeplink_for_user(email, uuid, state=None) -> str  # pure Python, for linkqr_lib

  # service control
  trusttunnel_restart_service() -> bool
  trusttunnel_reload_service() -> bool    # SIGHUP — reloads hosts.toml only
  trusttunnel_service_active() -> bool

  # install/uninstall (called from do_trusttunnel_menu)
  trusttunnel_install(domain, port=8443, acme_email="") -> bool
  trusttunnel_uninstall() -> bool

  # menu (called from _core.py dispatch)
  do_trusttunnel_menu() -> None
───────────────────────────────────────────────────────────────────────────────
"""
from __future__ import annotations

import base64
import hashlib
import json
import os
import re
import shutil
import struct
import subprocess
import tempfile
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional, Union, List, Dict, Tuple

# ── Constants ─────────────────────────────────────────────────────────────────
_STATE_FILE       = Path("/var/lib/xray-installer/trusttunnel.json")
_INSTALL_DIR      = Path("/opt/trusttunnel")
_BINARY_PATH      = _INSTALL_DIR / "trusttunnel_endpoint"
_WIZARD_PATH      = _INSTALL_DIR / "setup_wizard"
_VPN_TOML         = _INSTALL_DIR / "vpn.toml"
_HOSTS_TOML       = _INSTALL_DIR / "hosts.toml"
_CREDS_TOML       = _INSTALL_DIR / "credentials.toml"
_RULES_TOML       = _INSTALL_DIR / "rules.toml"
_SERVICE_NAME     = "trusttunnel"
_SYSTEMD_UNIT     = Path(f"/etc/systemd/system/{_SERVICE_NAME}.service")
_DEFAULT_PORT     = 8443
_METRICS_PORT     = 1987
_GPG_KEY_ID       = "28645AC9776EC4C00BCE2AFC0FE641E7235E2EC6"
_GPG_KEY_SERVER   = "keys.openpgp.org"
_VERSION_PIN      = "1.0.33"   # D6: latest public release as of Phase 0

# Cron — health check + traffic stats. Pattern follows hysteria2_watchdog.py
# (_CRON_FILE + _SCRIPT_FILE, install/remove pair, 5-min interval matches
# --h2-watchdog's 2-min and traffic-check's 5-min conventions).
_CRON_FILE        = Path("/etc/cron.d/trusttunnel")
_SCRIPT_FILE      = Path("/usr/local/bin/trusttunnel_cron.sh")
_PROJECT_ROOT     = Path("/opt/vless-ultimate")  # bootstrap.sh installs here
_CRON_INTERVAL_MIN = 5  # both health and stats run every 5 min

_LOG_FILE = Path("/var/log/xray-trusttunnel.log")


# =============================================================================
#  ОТЛОЖЕННАЯ ПРИВЯЗКА К ЯДРУ (_core.py)
# =============================================================================
def _core_module():
    """Возвращает модуль vless_installer._core (lazy import)."""
    import importlib
    return importlib.import_module("vless_installer._core")


# =============================================================================
#  ЛОГИРОВАНИЕ
# =============================================================================
def _log(level: str, msg: str) -> None:
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    line = f"[{ts}] [TRUSTTUNNEL] [{level}] {msg}"
    try:
        _LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
        with _LOG_FILE.open("a") as f:
            f.write(line + "\n")
    except Exception:
        pass
    try:
        core = _core_module()
        if hasattr(core, "log_to_file"):
            core.log_to_file(level, f"trusttunnel: {msg}")
    except Exception:
        pass


# =============================================================================
#  STATE FILE
# =============================================================================
def trusttunnel_load_state() -> dict:
    """Load /var/lib/xray-installer/trusttunnel.json. Returns {} if missing."""
    try:
        if _STATE_FILE.exists():
            data = json.loads(_STATE_FILE.read_text())
            if isinstance(data, dict):
                return data
    except Exception as e:
        _log("WARN", f"load_state: cannot read {_STATE_FILE}: {e}")
    return {}


def trusttunnel_save_state(state: dict) -> None:
    """Atomic write to trusttunnel.json with chmod 0o600."""
    _STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
    tmp = _STATE_FILE.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(state, indent=2, ensure_ascii=False))
    tmp.replace(_STATE_FILE)
    try:
        _STATE_FILE.chmod(0o600)
    except Exception:
        pass


def trusttunnel_is_installed() -> bool:
    """True if state['installed'] is True AND binary exists."""
    state = trusttunnel_load_state()
    return bool(state.get("installed")) and _BINARY_PATH.exists()


# =============================================================================
#  CREDENTIALS FILE CRUD (the core of the user_lifecycle integration)
# =============================================================================
# credentials.toml format (verified in Phase 0 by reading CONFIGURATION.md and
# by writing a 3-user file and generating deep-links for each):
#
#   [[client]]
#   username = "alice@example.com"
#   password = "abc123"
#
#   [[client]]
#   username = "bob@example.com"
#   password = "def456"
#   max_http2_conns = 16
#
# We parse/emit this with a minimal TOML reader/writer (no dependency on
# Python 3.11+ tomllib — the project supports older Pythons too). The format
# is simple enough: top-level array of tables, each with string keys and
# string/int values.

def _parse_credentials_toml(text: str) -> List[Dict]:
    """Minimal TOML parser for the credentials.toml format.
    Handles [[client]] blocks with username/password (strings) and
    max_http2_conns/max_http3_conns (ints). Does NOT support the full TOML
    spec — just enough for this file.
    """
    clients: List[Dict] = []
    current: Optional[Dict] = None
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line == "[[client]]":
            if current is not None:
                clients.append(current)
            current = {}
            continue
        if current is None:
            continue
        # key = "value"  or  key = 123
        m = re.match(r'^(\w+)\s*=\s*(.+)$', line)
        if not m:
            continue
        key, val = m.group(1), m.group(2).strip()
        if val.startswith('"') and val.endswith('"'):
            current[key] = val[1:-1]
        elif val.startswith("'") and val.endswith("'"):
            current[key] = val[1:-1]
        elif val.isdigit():
            current[key] = int(val)
        # else: skip unknown value types
    if current is not None:
        clients.append(current)
    return clients


def _format_credentials_toml(clients: List[Dict]) -> str:
    """Serialize a list of client dicts back to credentials.toml format."""
    lines: List[str] = []
    for c in clients:
        lines.append("[[client]]")
        lines.append(f'username = "{c.get("username", "")}"')
        lines.append(f'password = "{c.get("password", "")}"')
        if "max_http2_conns" in c and c["max_http2_conns"] is not None:
            lines.append(f'max_http2_conns = {int(c["max_http2_conns"])}')
        if "max_http3_conns" in c and c["max_http3_conns"] is not None:
            lines.append(f'max_http3_conns = {int(c["max_http3_conns"])}')
        lines.append("")
    return "\n".join(lines).rstrip() + "\n" if lines else ""


def _atomic_write_text(path: Path, text: str, mode: int = 0o600) -> None:
    """Atomic write via temp file + rename. Sets file mode."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text)
    try:
        tmp.chmod(mode)
    except Exception:
        pass
    tmp.replace(path)


def trusttunnel_list_users() -> List[Dict]:
    """Read credentials.toml, return list of client dicts.
    Returns [] if file missing or TrustTunnel not installed.
    """
    if not _CREDS_TOML.exists():
        return []
    try:
        text = _CREDS_TOML.read_text()
        return _parse_credentials_toml(text)
    except Exception as e:
        _log("ERROR", f"list_users: cannot read {_CREDS_TOML}: {e}")
        return []


def trusttunnel_user_exists(username: str) -> bool:
    """Check if a [[client]] block with the given username exists."""
    if not username:
        return False
    for c in trusttunnel_list_users():
        if c.get("username") == username:
            return True
    return False


def trusttunnel_add_user(username: str,
                          password: str,
                          max_http2_conns: Optional[int] = None,
                          max_http3_conns: Optional[int] = None) -> bool:
    """Add or update a user in credentials.toml. Idempotent (D5 requirement).

    If a [[client]] with the same username already exists, UPDATE its password
    and connection limits in place — do NOT create a duplicate block.

    Returns True on success, False on error. Does NOT restart the service —
    that's the caller's responsibility (batched via user_lifecycle).
    """
    if not username or not password:
        _log("ERROR", f"add_user: username and password required (got username={username!r})")
        return False
    try:
        clients = trusttunnel_list_users()
        # Idempotency: find existing entry by username
        found = False
        for c in clients:
            if c.get("username") == username:
                c["password"] = password
                if max_http2_conns is not None:
                    c["max_http2_conns"] = max_http2_conns
                elif "max_http2_conns" in c:
                    del c["max_http2_conns"]
                if max_http3_conns is not None:
                    c["max_http3_conns"] = max_http3_conns
                elif "max_http3_conns" in c:
                    del c["max_http3_conns"]
                found = True
                _log("INFO", f"add_user: updated existing entry for {username!r}")
                break
        if not found:
            new_entry: Dict = {"username": username, "password": password}
            if max_http2_conns is not None:
                new_entry["max_http2_conns"] = max_http2_conns
            if max_http3_conns is not None:
                new_entry["max_http3_conns"] = max_http3_conns
            clients.append(new_entry)
            _log("INFO", f"add_user: added new entry for {username!r}")
        _atomic_write_text(_CREDS_TOML, _format_credentials_toml(clients), mode=0o600)
        return True
    except Exception as e:
        _log("ERROR", f"add_user: exception for {username!r}: {e}")
        return False


def trusttunnel_remove_user(username: str) -> bool:
    """Remove a [[client]] block by username. Idempotent (no-op if not found).

    Returns True on success (including no-op), False on error.
    Does NOT restart the service — caller's responsibility.
    """
    if not username:
        return False
    try:
        clients = trusttunnel_list_users()
        new_clients = [c for c in clients if c.get("username") != username]
        if len(new_clients) == len(clients):
            _log("INFO", f"remove_user: {username!r} not found, noop")
            return True  # idempotent
        _atomic_write_text(_CREDS_TOML, _format_credentials_toml(new_clients), mode=0o600)
        _log("INFO", f"remove_user: removed {username!r}")
        return True
    except Exception as e:
        _log("ERROR", f"remove_user: exception for {username!r}: {e}")
        return False


def trusttunnel_update_user(username: str, **fields) -> bool:
    """Update specific fields (password, max_http2_conns, max_http3_conns) on
    an existing [[client]] block. Returns False if user not found.
    """
    if not username:
        return False
    try:
        clients = trusttunnel_list_users()
        found = False
        for c in clients:
            if c.get("username") == username:
                for k, v in fields.items():
                    if v is None:
                        c.pop(k, None)
                    else:
                        c[k] = v
                found = True
                break
        if not found:
            _log("WARN", f"update_user: {username!r} not found")
            return False
        _atomic_write_text(_CREDS_TOML, _format_credentials_toml(clients), mode=0o600)
        return True
    except Exception as e:
        _log("ERROR", f"update_user: exception for {username!r}: {e}")
        return False


# =============================================================================
#  DETERMINISTIC PASSWORD (D8)
# =============================================================================
def trusttunnel_derive_password(uuid_str: str) -> str:
    """Deterministic per-user password = SHA-256("trusttunnel-pass|" + uuid).

    Pattern copied from HYDRA-ULTIMATE (with a different prefix to avoid any
    collision if a user migrates between projects). Stable across reinstalls.
    Returns a 64-char lowercase hex string.
    """
    if not uuid_str:
        raise ValueError("uuid is required to derive TrustTunnel password")
    return hashlib.sha256(b"trusttunnel-pass|" + uuid_str.encode("utf-8")).hexdigest()


# =============================================================================
#  DEEP-LINK CODEC (pure Python, upstream tt://?<base64url-TLV> format)
# =============================================================================
# TLV wire format (verified in Phase 0 by reading deeplink/src/types.rs and
# by decoding a real deep-link with scripts/deeplink_to_config.py):
#   Each entry: varint(Tag) || varint(Length) || Value[Length bytes]
#   Varint is RFC 9000 §16 QUIC varint (2-bit length prefix, big-endian).
#
# Tag values:
#   0x00 version         (VarInt, default 1)
#   0x01 hostname        (UTF-8 string)        REQUIRED
#   0x02 addresses       (UTF-8 "host:port")   REQUIRED, may repeat
#   0x03 custom_sni      (UTF-8 string)
#   0x04 has_ipv6        (1 byte bool, default True)
#   0x05 username        (UTF-8 string)        REQUIRED
#   0x06 password        (UTF-8 string)        REQUIRED
#   0x07 skip_verification (1 byte bool)
#   0x08 certificate     (DER bytes, concatenated)
#   0x09 upstream_protocol (VarInt: 1=http2, 2=http3, default 1)
#   0x0A anti_dpi        (1 byte bool)
#   0x0B client_random_prefix (UTF-8 hex string)
#   0x0C name            (UTF-8 string, display name)
#   0x0D dns_upstreams   (varint-length-prefixed UTF-8 strings, concatenated)

_TT_VERSION = 1


def _varint_encode(n: int) -> bytes:
    """RFC 9000 §16 QUIC varint encoding (2-bit length prefix, big-endian)."""
    if n < 0:
        raise ValueError("varint cannot be negative")
    if n < 64:           # 6 bits, prefix 00
        return bytes([n])
    elif n < 16384:      # 14 bits, prefix 01
        return bytes([0x40 | (n >> 8), n & 0xFF])
    elif n < 1073741824: # 30 bits, prefix 10
        return bytes([0x80 | (n >> 24), (n >> 16) & 0xFF, (n >> 8) & 0xFF, n & 0xFF])
    elif n < 4611686018427387904:  # 62 bits, prefix 11
        return bytes([0xC0 | (n >> 56), (n >> 48) & 0xFF, (n >> 40) & 0xFF,
                      (n >> 32) & 0xFF, (n >> 24) & 0xFF, (n >> 16) & 0xFF,
                      (n >> 8) & 0xFF, n & 0xFF])
    else:
        raise ValueError("varint too large")


def _varint_decode(data: bytes, offset: int) -> Tuple[int, int]:
    """Decode a QUIC varint. Returns (value, new_offset)."""
    if offset >= len(data):
        raise ValueError("varint: unexpected end of data")
    first = data[offset]
    prefix = (first & 0xC0) >> 6
    if prefix == 0:
        return first & 0x3F, offset + 1
    elif prefix == 1:
        if offset + 1 >= len(data):
            raise ValueError("varint: truncated")
        return ((first & 0x3F) << 8) | data[offset + 1], offset + 2
    elif prefix == 2:
        if offset + 3 >= len(data):
            raise ValueError("varint: truncated")
        val = ((first & 0x3F) << 24) | (data[offset+1] << 16) | \
              (data[offset+2] << 8) | data[offset+3]
        return val, offset + 4
    else:  # prefix == 3
        if offset + 7 >= len(data):
            raise ValueError("varint: truncated")
        val = 0
        for i in range(8):
            if i == 0:
                val = (first & 0x3F) << (56 - i*8)
            else:
                val |= data[offset + i] << (56 - i*8)
        return val, offset + 8


def _tlv_encode(tag: int, value: bytes) -> bytes:
    """Encode a single TLV entry: varint(tag) || varint(len) || value."""
    return _varint_encode(tag) + _varint_encode(len(value)) + value


def _b64url_no_pad(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).decode("ascii").rstrip("=")


def _b64url_decode_no_pad(s: str) -> bytes:
    pad = "=" * (-len(s) % 4)
    return base64.urlsafe_b64decode(s + pad)


def trusttunnel_deeplink_encode(hostname: str,
                                addresses: List[str],
                                username: str,
                                password: str,
                                custom_sni: str = "",
                                has_ipv6: bool = True,
                                skip_verification: bool = False,
                                certificate_der: bytes = b"",
                                upstream_protocol: str = "http2",
                                anti_dpi: bool = False,
                                client_random_prefix: str = "",
                                name: str = "",
                                dns_upstreams: Optional[List[str]] = None) -> str:
    """Build a tt://?<base64url> deep-link URI using the upstream TLV format.

    This is a pure-Python reimplementation of deeplink/src/encode.rs. It lets
    linkqr_lib.py generate URIs without spawning the 17 MB endpoint binary on
    every /config or /qr request.

    For Let's Encrypt certs (system-verifiable), leave certificate_der empty —
    the upstream encoder omits tag 0x08 in that case, keeping the URI compact.
    """
    payload = b""
    # 0x00 version
    payload += _tlv_encode(0x00, _varint_encode(_TT_VERSION))
    # 0x01 hostname (required)
    payload += _tlv_encode(0x01, hostname.encode("utf-8"))
    # 0x02 addresses (required, may repeat — one TLV per address)
    for addr in addresses:
        payload += _tlv_encode(0x02, addr.encode("utf-8"))
    # 0x03 custom_sni (optional, omit if empty)
    if custom_sni:
        payload += _tlv_encode(0x03, custom_sni.encode("utf-8"))
    # 0x04 has_ipv6 (optional, default True — only emit if False to match upstream)
    if not has_ipv6:
        payload += _tlv_encode(0x04, bytes([0]))
    # 0x05 username (required)
    payload += _tlv_encode(0x05, username.encode("utf-8"))
    # 0x06 password (required)
    payload += _tlv_encode(0x06, password.encode("utf-8"))
    # 0x07 skip_verification (optional)
    if skip_verification:
        payload += _tlv_encode(0x07, bytes([1]))
    # 0x08 certificate (optional — only for self-signed)
    if certificate_der:
        payload += _tlv_encode(0x08, certificate_der)
    # 0x09 upstream_protocol (optional, default http2=1)
    proto_val = 2 if upstream_protocol == "http3" else 1
    if proto_val != 1:
        payload += _tlv_encode(0x09, _varint_encode(proto_val))
    # 0x0A anti_dpi (optional)
    if anti_dpi:
        payload += _tlv_encode(0x0A, bytes([1]))
    # 0x0B client_random_prefix (optional)
    if client_random_prefix:
        payload += _tlv_encode(0x0B, client_random_prefix.encode("utf-8"))
    # 0x0C name (optional)
    if name:
        payload += _tlv_encode(0x0C, name.encode("utf-8"))
    # 0x0D dns_upstreams (optional)
    if dns_upstreams:
        dns_blob = b""
        for dns in dns_upstreams:
            dns_bytes = dns.encode("utf-8")
            dns_blob += _varint_encode(len(dns_bytes)) + dns_bytes
        payload += _tlv_encode(0x0D, dns_blob)
    return "tt://?" + _b64url_no_pad(payload)


def trusttunnel_deeplink_decode(uri: str) -> Dict:
    """Decode a tt://?<base64url> URI into a dict of fields.

    Returns dict with keys: version, hostname, addresses (list), custom_sni,
    has_ipv6, username, password, skip_verification, certificate_der (bytes),
    upstream_protocol, anti_dpi, client_random_prefix, name, dns_upstreams (list).
    """
    s = uri.strip()
    # Accept both tt://?... and tt://... (v1.0.13 backward compat)
    if s.startswith("tt://?"):
        s = s[len("tt://?"):]
    elif s.startswith("tt://"):
        s = s[len("tt://"):]
    else:
        raise ValueError(f"not a tt:// URI: {uri[:40]}...")
    data = _b64url_decode_no_pad(s)
    result: Dict = {
        "version": 0,
        "hostname": "",
        "addresses": [],
        "custom_sni": "",
        "has_ipv6": True,
        "username": "",
        "password": "",
        "skip_verification": False,
        "certificate_der": b"",
        "upstream_protocol": "http2",
        "anti_dpi": False,
        "client_random_prefix": "",
        "name": "",
        "dns_upstreams": [],
    }
    offset = 0
    while offset < len(data):
        tag, offset = _varint_decode(data, offset)
        length, offset = _varint_decode(data, offset)
        if offset + length > len(data):
            raise ValueError(f"TLV tag {tag}: length {length} exceeds remaining data")
        value = data[offset:offset + length]
        offset += length
        if tag == 0x00:
            v, _ = _varint_decode(value, 0)
            result["version"] = v
        elif tag == 0x01:
            result["hostname"] = value.decode("utf-8")
        elif tag == 0x02:
            result["addresses"].append(value.decode("utf-8"))
        elif tag == 0x03:
            result["custom_sni"] = value.decode("utf-8")
        elif tag == 0x04:
            result["has_ipv6"] = bool(value[0]) if value else False
        elif tag == 0x05:
            result["username"] = value.decode("utf-8")
        elif tag == 0x06:
            result["password"] = value.decode("utf-8")
        elif tag == 0x07:
            result["skip_verification"] = bool(value[0]) if value else False
        elif tag == 0x08:
            result["certificate_der"] = value
        elif tag == 0x09:
            v, _ = _varint_decode(value, 0)
            result["upstream_protocol"] = "http3" if v == 2 else "http2"
        elif tag == 0x0A:
            result["anti_dpi"] = bool(value[0]) if value else False
        elif tag == 0x0B:
            result["client_random_prefix"] = value.decode("utf-8")
        elif tag == 0x0C:
            result["name"] = value.decode("utf-8")
        elif tag == 0x0D:
            # list of varint-length-prefixed UTF-8 strings
            up = []
            o = 0
            while o < len(value):
                slen, o = _varint_decode(value, o)
                if o + slen > len(value):
                    break
                up.append(value[o:o+slen].decode("utf-8"))
                o += slen
            result["dns_upstreams"] = up
    return result


def trusttunnel_generate_deeplink(username: str,
                                  address: Optional[str] = None,
                                  state: Optional[dict] = None) -> str:
    """Generate a deep-link by shelling out to the endpoint binary.

    This is the "ground truth" path — uses the real upstream binary which
    embeds the server's actual cert chain when needed. Used by the install
    wizard / status display. For high-frequency bot /config requests, use
    trusttunnel_deeplink_for_user() instead (pure Python).

    Raises ValueError if the user doesn't exist in credentials.toml (D4
    requirement: non-existent user protection — avoids Rust panic).
    """
    if not trusttunnel_user_exists(username):
        raise ValueError(
            f"TrustTunnel user {username!r} not found in credentials.toml — "
            f"refusing to invoke endpoint binary (would Rust panic)"
        )
    if state is None:
        state = trusttunnel_load_state()
    if not state.get("installed"):
        raise RuntimeError("TrustTunnel not installed")
    vpn_toml = state.get("vpn_toml", str(_VPN_TOML))
    hosts_toml = state.get("hosts_toml", str(_HOSTS_TOML))
    if not address:
        # Build address from state: domain:port
        domain = state.get("domain", "")
        port = state.get("listen_port", _DEFAULT_PORT)
        address = f"{domain}:{port}" if domain else f"0.0.0.0:{port}"
    cmd = [
        str(_BINARY_PATH), vpn_toml, hosts_toml,
        "-c", username,
        "-a", address,
        "--format", "deeplink",
    ]
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=15)
    except Exception as e:
        raise RuntimeError(f"trusttunnel_endpoint invocation failed: {e}")
    if r.returncode != 0:
        raise RuntimeError(
            f"trusttunnel_endpoint exited {r.returncode}: {r.stderr.strip()[:200]}"
        )
    # Output: first line is the tt://?... URI, second line is a blank, third
    # line starts with "To connect on mobile...". Extract just the URI.
    for line in r.stdout.splitlines():
        line = line.strip()
        if line.startswith("tt://"):
            return line
    raise RuntimeError(f"no tt:// URI in endpoint output: {r.stdout[:200]}")


def trusttunnel_deeplink_for_user(email: str,
                                  uuid_str: str,
                                  state: Optional[dict] = None) -> str:
    """Pure-Python deep-link builder for linkqr_lib.py.

    Returns "" if TrustTunnel not installed or user not in credentials.toml.
    Uses trusttunnel_deeplink_encode() with the server's hostname + address.
    For Let's Encrypt certs (system-verifiable), certificate_der is empty —
    the URI stays compact (matches upstream behavior).
    """
    if not email or not uuid_str:
        return ""
    if state is None:
        state = trusttunnel_load_state()
    if not state.get("installed"):
        return ""
    username = email  # D8: TrustTunnel username = email (verbatim)
    if not trusttunnel_user_exists(username):
        return ""
    password = trusttunnel_derive_password(uuid_str)
    hostname = state.get("domain", "")
    if not hostname:
        return ""
    port = state.get("listen_port", _DEFAULT_PORT)
    address = f"{hostname}:{port}"
    return trusttunnel_deeplink_encode(
        hostname=hostname,
        addresses=[address],
        username=username,
        password=password,
        upstream_protocol="http2",
    )


# =============================================================================
#  SERVICE CONTROL
# =============================================================================
def trusttunnel_restart_service() -> bool:
    """systemctl restart trusttunnel. Returns True on success."""
    try:
        r = subprocess.run(
            ["systemctl", "restart", _SERVICE_NAME],
            capture_output=True, text=True, timeout=30,
        )
        if r.returncode != 0:
            _log("ERROR", f"restart: systemctl failed: {r.stderr.strip()}")
            return False
        return True
    except Exception as e:
        _log("ERROR", f"restart: exception: {e}")
        return False


def trusttunnel_reload_service() -> bool:
    """systemctl reload trusttunnel (SIGHUP — reloads hosts.toml only).
    Used for cert renewal (D9: no restart needed, no active session disconnect).
    Returns True on success.
    """
    try:
        r = subprocess.run(
            ["systemctl", "reload", _SERVICE_NAME],
            capture_output=True, text=True, timeout=10,
        )
        if r.returncode != 0:
            _log("WARN", f"reload: systemctl failed: {r.stderr.strip()}")
            return False
        return True
    except Exception as e:
        _log("WARN", f"reload: exception: {e}")
        return False


def trusttunnel_service_active() -> bool:
    """systemctl is-active trusttunnel."""
    try:
        r = subprocess.run(
            ["systemctl", "is-active", "--quiet", _SERVICE_NAME],
            capture_output=True, timeout=5,
        )
        return r.returncode == 0
    except Exception:
        return False


# =============================================================================
#  INSTALL / UNINSTALL
# =============================================================================
_SYSTEMD_UNIT_TEMPLATE = """\
[Unit]
Description=TrustTunnel endpoint (VLESS Ultimate Installer)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory={install_dir}
ExecStart={binary} vpn.toml hosts.toml
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure
RestartSec=3
LimitNOFILE=1048576
StandardOutput=append:/var/log/trusttunnel-endpoint.log
StandardError=append:/var/log/trusttunnel-endpoint.log

[Install]
WantedBy=multi-user.target
"""


def _check_domain_available(domain: str) -> str:
    """D7: Check that domain is not used by another protocol.
    Returns "" if available, error message string if taken.
    """
    if not domain:
        return "domain is required"
    try:
        core = _core_module()
        # Check VLESS domain
        vless_domain = getattr(core, "PARAM_DOMAIN", "")
        if vless_domain and vless_domain == domain:
            return f"домен {domain} уже используется VLESS (PARAM_DOMAIN)"
        # Check NaiveProxy
        try:
            naive_state = json.loads(Path("/var/lib/xray-installer/naiveproxy.json").read_text())
            if naive_state.get("installed") and naive_state.get("domain") == domain:
                return f"домен {domain} уже используется NaiveProxy"
        except Exception:
            pass
        # Check FPTN
        try:
            fptn_state = json.loads(Path("/var/lib/xray-installer/fptn.json").read_text())
            if fptn_state.get("installed") and fptn_state.get("domain") == domain:
                return f"домен {domain} уже используется FPTN"
        except Exception:
            pass
        # Check MTProto own-site
        try:
            telemt_toml = Path("/etc/telemt/telemt.toml")
            if telemt_toml.exists():
                # crude grep for domain
                text = telemt_toml.read_text()
                if f'"{domain}"' in text or f"'{domain}'" in text:
                    return f"домен {domain} уже используется MTProto/Telemt"
        except Exception:
            pass
    except Exception as e:
        _log("WARN", f"_check_domain_available: {e}")
    return ""


def _check_port_available(port: int) -> str:
    """D2: Check that port is not used by another protocol.
    Returns "" if available, error message string if taken.
    """
    try:
        core = _core_module()
        if hasattr(core, "check_port_used_by_other_protocol"):
            return core.check_port_used_by_other_protocol(port, exclude_module="trusttunnel")
    except Exception as e:
        _log("WARN", f"_check_port_available: {e}")
    return ""


def _open_port(port: int) -> bool:
    """Open TCP+UDP port in ufw (or iptables fallback)."""
    try:
        if shutil.which("ufw"):
            for proto in ("tcp", "udp"):
                subprocess.run(
                    ["ufw", "allow", f"{port}/{proto}", "comment", "TRUSTTUNNEL"],
                    capture_output=True, timeout=10,
                )
            return True
    except Exception as e:
        _log("WARN", f"_open_port: ufw failed: {e}")
    # iptables fallback
    try:
        for proto in ("tcp", "udp"):
            subprocess.run(
                ["iptables", "-I", "INPUT", "1", "-p", proto,
                 "--dport", str(port), "-j", "ACCEPT"],
                capture_output=True, timeout=10,
            )
        return True
    except Exception as e:
        _log("ERROR", f"_open_port: iptables failed: {e}")
        return False


def _close_port(port: int) -> None:
    """Close TCP+UDP port in ufw (or iptables fallback)."""
    try:
        if shutil.which("ufw"):
            for proto in ("tcp", "udp"):
                subprocess.run(
                    ["ufw", "delete", "allow", f"{port}/{proto}"],
                    capture_output=True, timeout=10,
                )
            return
    except Exception:
        pass
    try:
        for proto in ("tcp", "udp"):
            subprocess.run(
                ["iptables", "-D", "INPUT", "-p", proto,
                 "--dport", str(port), "-j", "ACCEPT"],
                capture_output=True, timeout=10,
            )
    except Exception:
        pass


def _download_and_install_binary() -> Tuple[bool, str]:
    """Download prebuilt TrustTunnel binaries via download_manager.
    Returns (success, version_or_errormsg).
    """
    try:
        from vless_installer.modules.download_manager import fetch_package
        from vless_installer.modules.trusttunnel_packages import TRUSTTUNNEL_SPEC
        ok = fetch_package(TRUSTTUNNEL_SPEC, tag=f"v{_VERSION_PIN}", dry_run=False)
        if not ok:
            return False, "fetch_package failed — see logs above for manual hint"
        # Verify binary exists and is executable
        if not _BINARY_PATH.exists():
            return False, f"binary not found at {_BINARY_PATH} after fetch"
        _BINARY_PATH.chmod(0o755)
        if _WIZARD_PATH.exists():
            _WIZARD_PATH.chmod(0o755)
        # Get version
        try:
            r = subprocess.run([str(_BINARY_PATH), "--version"],
                               capture_output=True, text=True, timeout=5)
            version = r.stdout.strip() or _VERSION_PIN
        except Exception:
            version = _VERSION_PIN
        return True, version
    except Exception as e:
        return False, f"download failed: {e}"


def _import_gpg_key() -> bool:
    """Import the AdGuard GPG key for binary signature verification."""
    try:
        r = subprocess.run(
            ["gpg", "--keyserver", _GPG_KEY_SERVER, "--recv-keys", _GPG_KEY_ID],
            capture_output=True, text=True, timeout=30,
        )
        return r.returncode == 0
    except Exception as e:
        _log("WARN", f"_import_gpg_key: {e}")
        return False


def _verify_gpg_signature(binary_path: Path) -> bool:
    """Verify the GPG signature of a binary. Returns True if valid."""
    sig_path = binary_path.with_suffix(binary_path.suffix + ".sig")
    if not sig_path.exists():
        _log("WARN", f"_verify_gpg_signature: no .sig file at {sig_path}")
        return False
    try:
        r = subprocess.run(
            ["gpg", "--verify", str(sig_path), str(binary_path)],
            capture_output=True, text=True, timeout=15,
        )
        return r.returncode == 0
    except Exception as e:
        _log("WARN", f"_verify_gpg_signature: {e}")
        return False


def _install_systemd_unit(install_dir: Path) -> None:
    """Write the systemd unit file based on the template (D9: with ExecReload)."""
    unit_text = _SYSTEMD_UNIT_TEMPLATE.format(
        install_dir=install_dir,
        binary=_BINARY_PATH,
    )
    _SYSTEMD_UNIT.write_text(unit_text)
    subprocess.run(["systemctl", "daemon-reload"], capture_output=True, timeout=15)
    subprocess.run(["systemctl", "enable", _SERVICE_NAME], capture_output=True, timeout=10)


def _remove_systemd_unit() -> None:
    """Stop, disable, and remove the systemd unit."""
    subprocess.run(["systemctl", "stop", _SERVICE_NAME], capture_output=True, timeout=15)
    subprocess.run(["systemctl", "disable", _SERVICE_NAME], capture_output=True, timeout=10)
    if _SYSTEMD_UNIT.exists():
        _SYSTEMD_UNIT.unlink()
    subprocess.run(["systemctl", "daemon-reload"], capture_output=True, timeout=15)


def _install_cert_renewal_hook() -> None:
    """Install a certbot deploy hook so TrustTunnel reloads on LE renewal.
    Uses `systemctl reload` (SIGHUP) — no restart, no active session disconnect.
    """
    hook_dir = Path("/etc/letsencrypt/renewal-hooks/deploy")
    try:
        hook_dir.mkdir(parents=True, exist_ok=True)
    except Exception:
        return
    hook_path = hook_dir / "trusttunnel-reload.sh"
    hook_path.write_text("#!/bin/sh\nsystemctl reload trusttunnel || true\n")
    try:
        hook_path.chmod(0o755)
    except Exception:
        pass


def _remove_cert_renewal_hook() -> None:
    """Remove the certbot deploy hook for TrustTunnel."""
    hook_path = Path("/etc/letsencrypt/renewal-hooks/deploy/trusttunnel-reload.sh")
    if hook_path.exists():
        try:
            hook_path.unlink()
        except Exception:
            pass


# =============================================================================
#  CRON — health check + traffic stats (auto-installed on install, removed on uninstall)
# =============================================================================
# Pattern follows hysteria2_watchdog.py: a wrapper script in /usr/local/bin +
# a /etc/cron.d file. Both are installed together and removed together.
#
# Two cron entries in a single file (every 5 min):
#   */5 * * * * root /usr/local/bin/trusttunnel_cron.sh health
#   */5 * * * * root /usr/local/bin/trusttunnel_cron.sh stats
#
# The wrapper script dispatches to `main.py --trusttunnel-health` /
# `main.py --trusttunnel-stats`. We use a wrapper (not direct main.py calls
# in the cron line) so that:
#   - the cron file stays short and readable,
#   - we can add PYTHONPATH/cwd setup in one place if needed,
#   - matches the hysteria2_watchdog pattern.

# Note: we use __MAIN_PY__ / __INTERVAL__ / __SCRIPT__ placeholders + .replace()
# instead of str.format() because the bash script contains ${1:-health} which
# .format() would misinterpret as a positional arg placeholder.

_SCRIPT_TEMPLATE = """\
#!/bin/bash
# TrustTunnel cron wrapper — generated by VLESS Ultimate Installer
# Usage: trusttunnel_cron.sh {health|stats}
set -e
MODE="${1:-health}"
case "$MODE" in
    health)
        /usr/bin/python3 __MAIN_PY__ --trusttunnel-health 2>>/var/log/xray-trusttunnel.log
        ;;
    stats)
        /usr/bin/python3 __MAIN_PY__ --trusttunnel-stats 2>>/var/log/xray-trusttunnel.log
        ;;
    *)
        echo "Usage: $0 {health|stats}" >&2
        exit 1
        ;;
esac
"""

_CRON_TEMPLATE = """\
# TrustTunnel cron — VLESS Ultimate Installer
# Auto-generated; do not edit manually. Removed by trusttunnel_uninstall().
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

*/__INTERVAL__ * * * * root __SCRIPT__ health
*/__INTERVAL__ * * * * root __SCRIPT__ stats
"""


def _find_project_root() -> Path:
    """Find the project root (where main.py lives).
    Tries _PROJECT_ROOT first, then walks up from this file's location.
    """
    candidates = [
        _PROJECT_ROOT,
        Path("/opt/vless-ultimate"),
        Path("/opt/vless-installer"),
        Path(__file__).resolve().parent.parent.parent,  # vless_installer/modules/X.py → root
    ]
    for c in candidates:
        if (c / "main.py").exists():
            return c
    # Fallback: assume _PROJECT_ROOT
    return _PROJECT_ROOT


def _install_cron() -> None:
    """Install cron jobs for --trusttunnel-health and --trusttunnel-stats.
    Creates /usr/local/bin/trusttunnel_cron.sh + /etc/cron.d/trusttunnel.
    Idempotent — overwrites existing files.
    """
    project_root = _find_project_root()
    main_py = project_root / "main.py"
    if not main_py.exists():
        _log("WARN", f"_install_cron: main.py not found at {main_py}, cron will not work")
    # Write wrapper script (use .replace() — see comment near _SCRIPT_TEMPLATE)
    script_text = _SCRIPT_TEMPLATE.replace("__MAIN_PY__", str(main_py))
    try:
        _SCRIPT_FILE.write_text(script_text)
        _SCRIPT_FILE.chmod(0o755)
    except Exception as e:
        _log("ERROR", f"_install_cron: cannot write {_SCRIPT_FILE}: {e}")
        return
    # Write cron file
    cron_text = _CRON_TEMPLATE.replace("__INTERVAL__", str(_CRON_INTERVAL_MIN)) \
                              .replace("__SCRIPT__", str(_SCRIPT_FILE))
    try:
        _CRON_FILE.parent.mkdir(parents=True, exist_ok=True)
        _CRON_FILE.write_text(cron_text)
        _CRON_FILE.chmod(0o644)
    except Exception as e:
        _log("ERROR", f"_install_cron: cannot write {_CRON_FILE}: {e}")
        return
    _log("INFO", f"_install_cron: installed {_CRON_FILE} (interval={_CRON_INTERVAL_MIN}min)")


def _remove_cron() -> None:
    """Remove cron jobs for TrustTunnel. Idempotent."""
    for f in (_CRON_FILE, _SCRIPT_FILE):
        if f.exists():
            try:
                f.unlink()
                _log("INFO", f"_remove_cron: removed {f}")
            except Exception as e:
                _log("WARN", f"_remove_cron: cannot remove {f}: {e}")


def trusttunnel_cron_installed() -> bool:
    """Check if the cron file is installed. Used by tests + status display."""
    return _CRON_FILE.exists() and _SCRIPT_FILE.exists()


def trusttunnel_install(domain: str,
                        port: int = _DEFAULT_PORT,
                        acme_email: str = "") -> bool:
    """Full TrustTunnel install. Returns True on success.

    Steps:
      1. Pre-flight: check domain (D7) and port (D2) availability.
      2. Download prebuilt binaries via download_manager (D6).
      3. Verify GPG signatures (D6).
      4. Obtain Let's Encrypt cert via ssl_certbot.obtain_ssl_cert (D1).
      5. Run setup_wizard in non-interactive mode with --cert-type provided.
      6. Write systemd unit with ExecReload (D9).
      7. Install certbot deploy hook (D1).
      8. Open ufw/iptables ports (D2).
      9. Install cron jobs (--trusttunnel-health + --trusttunnel-stats, every 5 min).
     10. Start service, save state.
    """
    _log("INFO", f"install: domain={domain!r}, port={port}, acme_email={acme_email!r}")

    # 1. Pre-flight checks
    if not domain:
        _log("ERROR", "install: domain is required")
        return False
    domain_err = _check_domain_available(domain)
    if domain_err:
        _log("ERROR", f"install: {domain_err}")
        return False
    port_err = _check_port_available(port)
    if port_err:
        _log("ERROR", f"install: {port_err}")
        return False

    # 2. Download binaries
    _log("INFO", "install: downloading prebuilt binaries")
    ok, version_or_err = _download_and_install_binary()
    if not ok:
        _log("ERROR", f"install: {_download_and_install_binary.__name__}: {version_or_err}")
        return False
    version = version_or_err

    # 3. GPG verify
    _log("INFO", "install: importing AdGuard GPG key")
    _import_gpg_key()
    if not _verify_gpg_signature(_BINARY_PATH):
        _log("WARN", "install: GPG signature verification failed — continuing (binary already downloaded)")
        # Non-fatal: the binary is already in place. Log and continue.

    # 4. Obtain Let's Encrypt cert (D1)
    _log("INFO", f"install: obtaining Let's Encrypt cert for {domain}")
    try:
        from vless_installer.modules.ssl_certbot import obtain_ssl_cert
        obtain_ssl_cert(domain=domain)
    except Exception as e:
        _log("ERROR", f"install: obtain_ssl_cert failed: {e}")
        return False
    cert_chain = Path(f"/etc/letsencrypt/live/{domain}/fullchain.pem")
    cert_key = Path(f"/etc/letsencrypt/live/{domain}/privkey.pem")
    if not cert_chain.exists() or not cert_key.exists():
        _log("ERROR", f"install: cert files missing at {cert_chain}")
        return False

    # 5. Run setup_wizard non-interactive with --cert-type provided (D1)
    _log("INFO", "install: running setup_wizard (non-interactive)")
    listen_addr = f"0.0.0.0:{port}"
    # setup_wizard -c takes ONE user:pass pair. We'll use a placeholder admin
    # and then overwrite credentials.toml with our real users via CRUD API.
    # (The adapter's add() will populate real users after install.)
    admin_pass = trusttunnel_derive_password("00000000-0000-0000-0000-000000000000")
    cmd = [
        str(_WIZARD_PATH),
        "-m", "non-interactive",
        "-a", listen_addr,
        "-c", f"admin:{admin_pass}",
        "-n", domain,
        "--cert-type", "provided",
        "--cert-chain-path", str(cert_chain),
        "--cert-key-path", str(cert_key),
        "--lib-settings", str(_VPN_TOML),
        "--hosts-settings", str(_HOSTS_TOML),
    ]
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=60, cwd=str(_INSTALL_DIR))
    except Exception as e:
        _log("ERROR", f"install: setup_wizard invocation failed: {e}")
        return False
    if r.returncode != 0:
        _log("ERROR", f"install: setup_wizard exited {r.returncode}: {r.stderr[:300]}")
        return False

    # Append [metrics] block to vpn.toml so we can scrape /metrics (D5)
    try:
        with _VPN_TOML.open("a") as f:
            f.write(f"\n[metrics]\naddress = \"127.0.0.1:{_METRICS_PORT}\"\nrequest_timeout_secs = 3\n")
    except Exception as e:
        _log("WARN", f"install: cannot append [metrics] to vpn.toml: {e}")

    # 6. systemd unit (D9)
    _log("INFO", "install: writing systemd unit")
    _install_systemd_unit(_INSTALL_DIR)

    # 7. Cert renewal hook (D1)
    _install_cert_renewal_hook()

    # 8. Open ports (D2)
    _log("INFO", f"install: opening ports {port}/tcp + {port}/udp")
    _open_port(port)

    # 9. Install cron jobs (health check + traffic stats, every 5 min)
    _log("INFO", "install: installing cron jobs")
    _install_cron()

    # 10. Start service
    _log("INFO", "install: starting service")
    try:
        subprocess.run(["systemctl", "start", _SERVICE_NAME],
                       capture_output=True, text=True, timeout=15)
    except Exception as e:
        _log("ERROR", f"install: systemctl start failed: {e}")

    # Save state
    state = {
        "installed":       True,
        "version":         version,
        "domain":          domain,
        "listen_address":  listen_addr,
        "listen_port":     port,
        "cert_type":       "provided",
        "cert_chain_path": str(cert_chain),
        "cert_key_path":   str(cert_key),
        "install_dir":     str(_INSTALL_DIR),
        "binary_path":     str(_BINARY_PATH),
        "wizard_path":     str(_WIZARD_PATH),
        "vpn_toml":        str(_VPN_TOML),
        "hosts_toml":      str(_HOSTS_TOML),
        "creds_toml":      str(_CREDS_TOML),
        "rules_toml":      str(_RULES_TOML),
        "metrics_port":    _METRICS_PORT,
        "installed_at":    datetime.now(timezone.utc).isoformat(),
    }
    trusttunnel_save_state(state)
    _log("INFO", f"install: done, version={version}, port={port}")
    return True


def trusttunnel_uninstall() -> bool:
    """Full uninstall. Returns True on success."""
    _log("INFO", "uninstall: starting")
    state = trusttunnel_load_state()
    port = state.get("listen_port", _DEFAULT_PORT)

    # Stop + remove systemd unit
    _remove_systemd_unit()

    # Close ports
    _close_port(port)

    # Remove cert renewal hook
    _remove_cert_renewal_hook()

    # Remove cron jobs (health + stats) — no hanging cron entries
    _remove_cron()

    # Remove install dir (binaries + configs)
    try:
        if _INSTALL_DIR.exists():
            shutil.rmtree(_INSTALL_DIR)
    except Exception as e:
        _log("WARN", f"uninstall: cannot remove {_INSTALL_DIR}: {e}")

    # Clear state
    try:
        _STATE_FILE.unlink()
    except Exception:
        pass
    _log("INFO", "uninstall: done")
    return True


# =============================================================================
#  STATUS / GUIDE
# =============================================================================
def trusttunnel_show_status() -> None:
    """Print TrustTunnel status to stdout (called from menu)."""
    state = trusttunnel_load_state()
    if not state.get("installed"):
        print("TrustTunnel: NOT installed")
        return
    print(f"TrustTunnel v{state.get('version', '?')}")
    print(f"  Domain:     {state.get('domain', '?')}")
    print(f"  Listen:     {state.get('listen_address', '?')}  (TCP+UDP)")
    print(f"  Cert:       {state.get('cert_chain_path', '?')}")
    print(f"  Metrics:    http://127.0.0.1:{state.get('metrics_port', _METRICS_PORT)}/metrics")
    print(f"  Service:    {'active' if trusttunnel_service_active() else 'INACTIVE'}")
    print(f"  Cron:       {'installed (/etc/cron.d/trusttunnel)' if trusttunnel_cron_installed() else 'NOT installed'}")
    users = trusttunnel_list_users()
    print(f"  Users:      {len(users)}")
    for u in users:
        print(f"    - {u.get('username', '?')}")


def trusttunnel_show_guide() -> None:
    """Print client connection guide (called from menu)."""
    state = trusttunnel_load_state()
    if not state.get("installed"):
        print("TrustTunnel не установлен.")
        return
    print("\n=== TrustTunnel — подключение клиента ===\n")
    print("Клиентское приложение: TrustTunnel Flutter Client")
    print("  https://github.com/TrustTunnel/TrustTunnelClient\n")
    print("Способ подключения:")
    print("  1. Установите TrustTunnel клиент на устройство (iOS/Android/macOS).")
    print("  2. Получите tt:// ссылку у администратора или через self-service бота.")
    print("  3. Отсканируйте QR-код или вставьте ссылку в приложение.\n")
    print("Формат ссылки: tt://?<base64url> (upstream TLV-формат)\n")


# =============================================================================
#  MENU
# =============================================================================
def do_trusttunnel_menu() -> None:
    """Main TrustTunnel menu (called from _core.py dispatch, entry 18)."""
    # Lazy core access for colors / input helpers
    try:
        core = _core_module()
        CYAN = getattr(core, "CYAN", "")
        GREEN = getattr(core, "GREEN", "")
        YELLOW = getattr(core, "YELLOW", "")
        NC = getattr(core, "NC", "")
        warn = getattr(core, "warn", lambda m: print(m))
        ok_msg = getattr(core, "ok", lambda m: print(m))
    except Exception:
        CYAN = GREEN = YELLOW = NC = ""
        warn = lambda m: print(m)
        ok_msg = lambda m: print(m)

    state = trusttunnel_load_state()
    installed = bool(state.get("installed"))

    while True:
        print()
        print(f"{CYAN}═══ TrustTunnel {'[' + state.get('version','') + ']' if installed else '[не установлен]'} ═══{NC}")
        print(f"  {CYAN}1{NC}  {'Переустановить' if installed else 'Установить'} TrustTunnel")
        print(f"  {CYAN}2{NC}  Статус")
        print(f"  {CYAN}3{NC}  Список пользователей")
        if installed:
            print(f"  {CYAN}4{NC}  Добавить пользователя (тест)")
            print(f"  {CYAN}5{NC}  Сгенерировать deep-link для пользователя")
            print(f"  {CYAN}6{NC}  Перезапустить сервис")
            print(f"  {CYAN}7{NC}  Инструкция для клиента")
            print(f"  {CYAN}8{NC}  Удалить TrustTunnel")
        print(f"  {CYAN}0{NC}  Назад")
        print()
        try:
            choice = input(f"{CYAN}Выбор:{NC} ").strip()
        except (EOFError, KeyboardInterrupt):
            break

        if choice == "0":
            break
        elif choice == "1":
            if installed:
                print(f"{YELLOW}Переустановка удалит текущую конфигурацию.{NC}")
                domain = state.get("domain", "")
                port = state.get("listen_port", _DEFAULT_PORT)
            else:
                try:
                    domain = input("Домен (например tt.example.com): ").strip()
                    port_str = input(f"Порт [Enter={_DEFAULT_PORT}]: ").strip()
                    port = int(port_str) if port_str.isdigit() else _DEFAULT_PORT
                except (EOFError, KeyboardInterrupt):
                    continue
            acme_email = ""
            try:
                acme_email = input("Email для Let's Encrypt (Enter для пропуска): ").strip()
            except (EOFError, KeyboardInterrupt):
                pass
            if trusttunnel_install(domain, port, acme_email):
                ok_msg("TrustTunnel установлен успешно.")
            else:
                warn("Установка не удалась — см. /var/log/xray-trusttunnel.log")
            time.sleep(2)
        elif choice == "2":
            trusttunnel_show_status()
            try:
                input("\nНажмите Enter для продолжения...")
            except (EOFError, KeyboardInterrupt):
                pass
        elif choice == "3":
            users = trusttunnel_list_users()
            if not users:
                print("Пользователей нет.")
            else:
                for u in users:
                    print(f"  - {u.get('username', '?')}")
            try:
                input("\nНажмите Enter...")
            except (EOFError, KeyboardInterrupt):
                pass
        elif choice == "4" and installed:
            try:
                email = input("Email нового пользователя: ").strip()
                uuid_str = input("UUID пользователя: ").strip()
            except (EOFError, KeyboardInterrupt):
                continue
            if not email or not uuid_str:
                warn("Email и UUID обязательны")
                time.sleep(1)
                continue
            password = trusttunnel_derive_password(uuid_str)
            if trusttunnel_add_user(email, password):
                # Single manual op — restart immediately (no batching needed)
                trusttunnel_restart_service()
                ok_msg(f"Пользователь {email} добавлен")
            else:
                warn("Не удалось добавить пользователя")
            time.sleep(1)
        elif choice == "5" and installed:
            try:
                email = input("Email пользователя: ").strip()
            except (EOFError, KeyboardInterrupt):
                continue
            try:
                link = trusttunnel_generate_deeplink(email)
                print(f"\n{GREEN}Deep-link:{NC}")
                print(link)
                print(f"\nQR: https://trusttunnel.org/qr.html#tt={link[len('tt://?'):]}")
            except ValueError as e:
                warn(str(e))
            except Exception as e:
                warn(f"Ошибка: {e}")
            try:
                input("\nНажмите Enter...")
            except (EOFError, KeyboardInterrupt):
                pass
        elif choice == "6" and installed:
            if trusttunnel_restart_service():
                ok_msg("Сервис перезапущен")
            else:
                warn("Не удалось перезапустить сервис")
            time.sleep(1)
        elif choice == "7" and installed:
            trusttunnel_show_guide()
            try:
                input("\nНажмите Enter...")
            except (EOFError, KeyboardInterrupt):
                pass
        elif choice == "8" and installed:
            try:
                confirm = input("Точно удалить TrustTunnel? (yes/no): ").strip()
            except (EOFError, KeyboardInterrupt):
                continue
            if confirm.lower() == "yes":
                if trusttunnel_uninstall():
                    ok_msg("TrustTunnel удалён")
                else:
                    warn("Ошибка при удалении")
            time.sleep(1)
        else:
            warn(f"Неверный выбор: {choice}")
            time.sleep(1)
