#!/usr/bin/env python3
"""
tests/test_trusttunnel_user_lifecycle.py
───────────────────────────────────────────────────────────────────────────────
Unit-тесты для TrustTunnelAdapter + batched restart mechanism in user_lifecycle.py.

ПОКРЫТИЕ (по требованиям Phase 1):
  1. Батчинг рестартов: 5 пользователей → ровно 1 restart за весь cron pass.
  2. Rollback при частичном сбое: TrustTunnel-синхронизация падает в середине
     мультипротокольного add_user → откатываются ВСЕ файлы, рестарт НЕ происходит.
  3. Non-existent user protection: deep-link для отсутствующего username →
     вменяемое ValueError ДО вызова бинарника (не Rust panic).
  4. Идемпотентность add(): повторный вызов не плодит дубли [[client]].
  5. Регрессия: существующий test_user_lifecycle.py проходит без изменений
     (батчинг-механизм не ломает поведение остальных 8 протоколов).

REAL FORMATS (из Phase 0, не придуманные):
  • credentials.toml — реальный TOML-формат [[client]] блоков (подтверждён
    чтением CONFIGURATION.md + записи 3-user файла и генерации deep-link'ов
    для каждого в Phase 0 sanity-check).
  • tt://?<base64url> deep-link — реальный upstream TLV-формат (подтверждён
    декодированием через scripts/deeplink_to_config.py).
  • trusttunnel_endpoint --version → "1.0.33" (реальный вывод).
"""
from __future__ import annotations

import json
import os
import shutil
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch, MagicMock

_PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_PROJECT_ROOT))


def _setup_core_in_sysmodules():
    """Создаёт фейковый vless_installer._core в sys.modules."""
    core_path = _PROJECT_ROOT / "vless_installer" / "_core.py"
    src = core_path.read_text()
    g = {}
    with patch.object(Path, 'mkdir', lambda self, *a, **kw: None), \
         patch.object(Path, 'touch', lambda self, *a, **kw: None), \
         patch.object(Path, 'chmod', lambda self, *a, **kw: None), \
         patch('os.chown', lambda *a, **kw: None), \
         patch('os.geteuid', return_value=0):
        exec(compile(src, str(core_path), "exec"), g)
    import types
    fake_core = types.ModuleType("vless_installer._core")
    fake_core.__dict__.update(g)
    sys.modules["vless_installer._core"] = fake_core


# =============================================================================
#  Test fixture: realistic credentials.toml content (from Phase 0 sanity-check)
# =============================================================================
_REAL_CREDS_TOML = """\
[[client]]
username = "alice@example.com"
password = "alice-pass"

[[client]]
username = "bob@example.com"
password = "bob-pass"
max_http2_conns = 16

[[client]]
username = "carol@example.com"
password = "carol-pass"
max_http3_conns = 2
"""

# Real deep-link generated by trusttunnel_endpoint v1.0.33 in Phase 0
# (decoded and verified via scripts/deeplink_to_config.py).
_REAL_DEEPLINK_ALICE = (
    "tt://?AAEBARB0ZXN0LmV4YW1wbGUuY29tBQVhbGljZQYKYWxpY2UtcGFzcwIR"
    "MjAzLjAuMTEzLjEwOjg0NDMIQW8wggFrMIIBEaADAgECAhRudS_h5WQZQSCi"
    "ohxold3qFw-0EjAKBggqhkjOPQQDAjAbMRkwFwYDVQQDDBB0ZXN0LmV4YW1w"
    "bGUuY29tMB4XDTI2MDcxNDAwMDAwMFoXDTI3MDcxNDAwMDAwMFowGzEZMBcG"
    "A1UEAwwQdGVzdC5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEH"
    "A0IABIikkHEVnjGUhyyApK0VAm3Blck2ou42ZAR5mEJCL-nTtWbO-RQwX5MZ"
    "ioag_JgZSMChDqDV3e6grmiT3ozXqSOjMzAxMC8GA1UdEQQoMCaCEHRlc3Qu"
    "ZXhhbXBsZS5jb22CEioudGVzdC5leGFtcGxlLmNvbTAKBggqhkjOPQQDAgNI"
    "ADBFAiEAyR9R0y6ueyDP_jZqAxexSF3E9rtGkBLwcEl0pIqvW1wCIEIhrW65"
    "E4xmp1dfGx1vgI5MZPWHedTBklNLCHcujVD1"
)


class _TrustTunnelLifecycleFixture:
    """Helper: sets up a tempdir with realistic state files and patches
    all the module-level paths so TrustTunnelAdapter operates on temp files."""

    def __init__(self):
        self.tmpdir = Path(tempfile.mkdtemp())
        self.creds_toml = self.tmpdir / "credentials.toml"
        self.state_json = self.tmpdir / "trusttunnel.json"
        self.users_json = self.tmpdir / "users.json"
        self.users_json.write_text("[]")
        self.binary_path = self.tmpdir / "trusttunnel_endpoint"
        self.binary_path.write_text("#!/bin/sh\nexit 0\n")
        self.binary_path.chmod(0o755)

    def write_creds(self, text: str):
        self.creds_toml.write_text(text)

    def write_state(self, state: dict):
        self.state_json.write_text(json.dumps(state, indent=2))

    def cleanup(self):
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    def patches(self):
        """Returns a list of patch() context managers to apply."""
        return [
            patch("vless_installer.modules.trusttunnel._CREDS_TOML", self.creds_toml),
            patch("vless_installer.modules.trusttunnel._STATE_FILE", self.state_json),
            patch("vless_installer.modules.trusttunnel._BINARY_PATH", self.binary_path),
            patch("vless_installer.modules.user_lifecycle._TRUSTTUNNEL_CREDS_FILE", self.creds_toml),
            patch("vless_installer.modules.user_lifecycle._TRUSTTUNNEL_STATE_FILE", self.state_json),
            patch("vless_installer.modules.user_lifecycle._USERS_FILE", self.users_json),
        ]


# =============================================================================
#  TEST 4: Idempotency — add() does not create duplicate [[client]] blocks
# =============================================================================
class TestTrustTunnelAdapterIdempotency(unittest.TestCase):
    """Requirement 5: повторный вызов add() для уже существующего юзера не
    должен создавать дубликат [[client]]-блока."""

    def setUp(self):
        _setup_core_in_sysmodules()
        self.fx = _TrustTunnelLifecycleFixture()
        self.fx.write_creds(_REAL_CREDS_TOML)
        self.fx.write_state({
            "installed": True,
            "version": "1.0.33",
            "domain": "tt.example.com",
            "listen_port": 8443,
        })
        for p in self.fx.patches():
            p.start()
            self.addCleanup(p.stop)

    def tearDown(self):
        self.fx.cleanup()

    def test_add_existing_user_updates_in_place(self):
        """Adding alice twice should NOT create a second [[client]] block."""
        from vless_installer.modules import user_lifecycle
        # Reset batch state
        user_lifecycle._PENDING_RESTARTS = set()
        user_lifecycle._BATCH_DEPTH = 0

        # alice already has password "alice-pass" in _REAL_CREDS_TOML.
        # We call add() with a DIFFERENT uuid → different derived password.
        uuid1 = "11111111-1111-1111-1111-111111111111"
        uuid2 = "22222222-2222-2222-2222-222222222222"

        # First add: updates alice's password to derive(uuid1)
        ok1 = user_lifecycle.TrustTunnelAdapter.add("alice@example.com", uuid=uuid1)
        self.assertTrue(ok1, "first add should succeed")

        # Read credentials.toml — should still have exactly 3 users
        from vless_installer.modules.trusttunnel import trusttunnel_list_users
        users_after_first = trusttunnel_list_users()
        self.assertEqual(len(users_after_first), 3,
                         f"expected 3 users after first add, got {len(users_after_first)}")

        # Find alice — her password should be updated
        alice = next(u for u in users_after_first if u["username"] == "alice@example.com")
        import hashlib
        expected_pass = hashlib.sha256(b"trusttunnel-pass|" + uuid1.encode()).hexdigest()
        self.assertEqual(alice["password"], expected_pass)

        # Second add: updates alice's password to derive(uuid2)
        ok2 = user_lifecycle.TrustTunnelAdapter.add("alice@example.com", uuid=uuid2)
        self.assertTrue(ok2, "second add should succeed")

        users_after_second = trusttunnel_list_users()
        self.assertEqual(len(users_after_second), 3,
                         f"expected 3 users after second add (no duplicate), got {len(users_after_second)}")

        # alice's password should now be derive(uuid2)
        alice = next(u for u in users_after_second if u["username"] == "alice@example.com")
        expected_pass2 = hashlib.sha256(b"trusttunnel-pass|" + uuid2.encode()).hexdigest()
        self.assertEqual(alice["password"], expected_pass2)

    def test_add_new_user_appends(self):
        """Adding a brand-new user should append a 4th [[client]] block."""
        from vless_installer.modules import user_lifecycle
        user_lifecycle._PENDING_RESTARTS = set()
        user_lifecycle._BATCH_DEPTH = 0

        uuid_str = "33333333-3333-3333-3333-333333333333"
        ok = user_lifecycle.TrustTunnelAdapter.add("dave@example.com", uuid=uuid_str)
        self.assertTrue(ok)

        from vless_installer.modules.trusttunnel import trusttunnel_list_users
        users = trusttunnel_list_users()
        self.assertEqual(len(users), 4, f"expected 4 users, got {len(users)}")
        dave = next(u for u in users if u["username"] == "dave@example.com")
        self.assertIsNotNone(dave)


# =============================================================================
#  TEST 1: Batching — 5 users → exactly 1 restart
# =============================================================================
class TestBatchedRestarts(unittest.TestCase):
    """Requirement 2: 5 users blocked in one cron pass → exactly 1 restart,
    not 5."""

    def setUp(self):
        _setup_core_in_sysmodules()
        self.fx = _TrustTunnelLifecycleFixture()
        # Start with 5 users in credentials.toml
        creds = ""
        for i in range(5):
            creds += f'[[client]]\nusername = "user{i}@example.com"\npassword = "pass{i}"\n\n'
        self.fx.write_creds(creds.strip() + "\n")
        self.fx.write_state({
            "installed": True,
            "version": "1.0.33",
            "domain": "tt.example.com",
            "listen_port": 8443,
        })
        for p in self.fx.patches():
            p.start()
            self.addCleanup(p.stop)
        # Mock the restart function so we can count calls
        self.restart_calls = 0
        self.restart_patch = patch(
            "vless_installer.modules.trusttunnel.trusttunnel_restart_service",
            side_effect=self._count_restart,
        )
        self.restart_patch.start()
        self.addCleanup(self.restart_patch.stop)

    def tearDown(self):
        self.fx.cleanup()

    def _count_restart(self):
        self.restart_calls += 1
        return True

    def test_batch_context_collapses_5_blocks_to_1_restart(self):
        """5 block_user() calls inside batch_context → 1 restart."""
        from vless_installer.modules import user_lifecycle
        user_lifecycle._PENDING_RESTARTS = set()
        user_lifecycle._BATCH_DEPTH = 0

        # Also mock VLESS adapter (since users.json is empty, block is a noop
        # but we need it to not crash)
        with patch.object(user_lifecycle.VlessAdapter, "block", return_value=True):
            with user_lifecycle.batch_context():
                for i in range(5):
                    user_lifecycle.block_user(
                        f"user{i}@example.com",
                        reason="traffic_limit",
                        protocols=["trusttunnel"],  # skip vless to keep it simple
                    )
        # After batch_context exits, restart should have been called exactly ONCE
        self.assertEqual(self.restart_calls, 1,
                         f"expected 1 restart for 5 batched blocks, got {self.restart_calls}")

    def test_no_batch_context_5_separate_ops_5_restarts(self):
        """Without batch_context, 5 separate block_user() calls → 5 restarts.
        This confirms the batching is what collapses them."""
        from vless_installer.modules import user_lifecycle
        user_lifecycle._PENDING_RESTARTS = set()
        user_lifecycle._BATCH_DEPTH = 0

        with patch.object(user_lifecycle.VlessAdapter, "block", return_value=True):
            for i in range(5):
                # Re-write creds each iteration so the user exists for block
                creds = ""
                for j in range(5):
                    if j == i:
                        continue  # simulate the user being blocked (removed)
                    creds += f'[[client]]\nusername = "user{j}@example.com"\npassword = "pass{j}"\n\n'
                # Actually, block = remove. Let's just re-add all 5 each time
                # so the user exists when we try to block it.
                creds = ""
                for j in range(5):
                    creds += f'[[client]]\nusername = "user{j}@example.com"\npassword = "pass{j}"\n\n'
                self.fx.write_creds(creds.strip() + "\n")
                user_lifecycle.block_user(
                    f"user{i}@example.com",
                    reason="traffic_limit",
                    protocols=["trusttunnel"],
                )
        self.assertEqual(self.restart_calls, 5,
                         f"expected 5 restarts without batching, got {self.restart_calls}")

    def test_nested_batch_context_still_one_restart(self):
        """Nested batch_context() should still produce only 1 restart."""
        from vless_installer.modules import user_lifecycle
        user_lifecycle._PENDING_RESTARTS = set()
        user_lifecycle._BATCH_DEPTH = 0

        with patch.object(user_lifecycle.VlessAdapter, "block", return_value=True):
            with user_lifecycle.batch_context():
                with user_lifecycle.batch_context():
                    user_lifecycle.block_user("user0@example.com",
                                              protocols=["trusttunnel"])
                user_lifecycle.block_user("user1@example.com",
                                          protocols=["trusttunnel"])
        self.assertEqual(self.restart_calls, 1,
                         f"nested batch should produce 1 restart, got {self.restart_calls}")


# =============================================================================
#  TEST 2: Rollback — partial failure in multi-protocol add_user
# =============================================================================
class TestRollbackOnPartialFailure(unittest.TestCase):
    """Requirement 3: TrustTunnel-синхронизация падает в середине
    мультипротокольного add_user → откатываются ВСЕ файлы, рестарт НЕ происходит."""

    def setUp(self):
        _setup_core_in_sysmodules()
        self.fx = _TrustTunnelLifecycleFixture()
        self.fx.write_creds(_REAL_CREDS_TOML)
        self.fx.write_state({
            "installed": True,
            "version": "1.0.33",
            "domain": "tt.example.com",
            "listen_port": 8443,
        })
        for p in self.fx.patches():
            p.start()
            self.addCleanup(p.stop)
        self.restart_calls = 0
        self.restart_patch = patch(
            "vless_installer.modules.trusttunnel.trusttunnel_restart_service",
            side_effect=self._count_restart,
        )
        self.restart_patch.start()
        self.addCleanup(self.restart_patch.stop)

    def tearDown(self):
        self.fx.cleanup()

    def _count_restart(self):
        self.restart_calls += 1
        return True

    def test_rollback_restores_creds_and_no_restart(self):
        """If TrustTunnel add fails AFTER VLESS add succeeds, both files
        should be rolled back AND no restart should happen."""
        from vless_installer.modules import user_lifecycle
        user_lifecycle._PENDING_RESTARTS = set()
        user_lifecycle._BATCH_DEPTH = 0

        # Save original creds for later comparison
        original_creds = self.fx.creds_toml.read_text()
        original_users = self.fx.users_json.read_text()

        # Mock VlessAdapter.add to succeed (simulates VLESS user created)
        # But then mock trusttunnel_add_user to FAIL (simulates creds.toml
        # write failure — e.g. disk full or permissions).
        with patch.object(user_lifecycle.VlessAdapter, "add", return_value=True) as mock_vless_add, \
             patch("vless_installer.modules.trusttunnel.trusttunnel_add_user",
                   side_effect=IOError("simulated disk full")):
            result = user_lifecycle.add_user(
                email="newuser@example.com",
                protocols=["vless", "trusttunnel"],
                uuid_str="55555555-5555-5555-5555-555555555555",
            )

        # add_user should have failed
        self.assertFalse(result["success"],
                         f"add_user should fail when trusttunnel.add raises, got: {result}")
        self.assertIn("trusttunnel", result["failed"])

        # credentials.toml should be UNCHANGED (rolled back)
        # Note: VlessAdapter.add was mocked to return True without actually
        # touching users.json, so users.json is also unchanged.
        self.assertEqual(self.fx.creds_toml.read_text(), original_creds,
                         "credentials.toml should be rolled back to original")
        self.assertEqual(self.fx.users_json.read_text(), original_users,
                         "users.json should be rolled back to original")

        # CRITICAL: no restart should have happened for the rolled-back
        # TrustTunnel operation.
        self.assertEqual(self.restart_calls, 0,
                         f"no restart should happen on rollback, got {self.restart_calls}")

        # _PENDING_RESTARTS should be empty (cancelled by rollback)
        self.assertEqual(user_lifecycle._PENDING_RESTARTS, set(),
                         "pending restarts should be cancelled on rollback")

    def test_rollback_when_trusttunnel_is_first_protocol(self):
        """Even if TrustTunnel is the FIRST protocol and fails, rollback
        should still work and no restart should happen."""
        from vless_installer.modules import user_lifecycle
        user_lifecycle._PENDING_RESTARTS = set()
        user_lifecycle._BATCH_DEPTH = 0

        original_creds = self.fx.creds_toml.read_text()

        with patch("vless_installer.modules.trusttunnel.trusttunnel_add_user",
                   side_effect=IOError("simulated failure")):
            result = user_lifecycle.add_user(
                email="newuser@example.com",
                protocols=["trusttunnel"],  # trusttunnel only
                uuid_str="66666666-6666-6666-6666-666666666666",
            )

        self.assertFalse(result["success"])
        self.assertEqual(self.fx.creds_toml.read_text(), original_creds,
                         "creds should be unchanged after failed add")
        self.assertEqual(self.restart_calls, 0,
                         "no restart on failed add")
        self.assertEqual(user_lifecycle._PENDING_RESTARTS, set())


# =============================================================================
#  TEST 3: Non-existent user protection
# =============================================================================
class TestNonExistentUserProtection(unittest.TestCase):
    """Requirement 4: deep-link для отсутствующего username → вменяемое
    ValueError ДО вызова бинарника (не Rust panic)."""

    def setUp(self):
        _setup_core_in_sysmodules()
        self.fx = _TrustTunnelLifecycleFixture()
        self.fx.write_creds(_REAL_CREDS_TOML)
        self.fx.write_state({
            "installed": True,
            "version": "1.0.33",
            "domain": "tt.example.com",
            "listen_port": 8443,
        })
        for p in self.fx.patches():
            p.start()
            self.addCleanup(p.stop)

    def tearDown(self):
        self.fx.cleanup()

    def test_generate_deeplink_nonexistent_user_raises_valueerror(self):
        """trusttunnel_generate_deeplink for a non-existent user should
        raise ValueError BEFORE invoking the binary."""
        from vless_installer.modules.trusttunnel import trusttunnel_generate_deeplink

        # eve is NOT in _REAL_CREDS_TOML (only alice, bob, carol)
        with self.assertRaises(ValueError) as ctx:
            trusttunnel_generate_deeplink("eve@example.com")

        # The error message should mention the username and that it's not found
        err_msg = str(ctx.exception)
        self.assertIn("eve@example.com", err_msg)
        self.assertIn("not found", err_msg.lower())

    def test_generate_deeplink_existing_user_works(self):
        """For an existing user, the function should proceed (and either
        succeed or fail at the binary invocation, but NOT raise ValueError
        for user-not-found)."""
        from vless_installer.modules.trusttunnel import trusttunnel_generate_deeplink

        # Mock the subprocess call so we don't need a real binary
        mock_result = MagicMock(returncode=0, stdout="tt://?abc123\n\nTo connect...\n", stderr="")
        with patch("subprocess.run", return_value=mock_result):
            link = trusttunnel_generate_deeplink("alice@example.com")
        self.assertTrue(link.startswith("tt://"),
                        f"expected tt:// URI, got: {link[:40]}")

    def test_deeplink_for_user_returns_empty_for_nonexistent(self):
        """trusttunnel_deeplink_for_user (pure Python, used by linkqr_lib)
        should return "" for a non-existent user — no exception."""
        from vless_installer.modules.trusttunnel import trusttunnel_deeplink_for_user

        # eve is not in credentials.toml
        link = trusttunnel_deeplink_for_user("eve@example.com", "some-uuid")
        self.assertEqual(link, "",
                         "should return empty string for non-existent user")

    def test_deeplink_for_user_returns_empty_when_not_installed(self):
        """When TrustTunnel is not installed, should return ""."""
        from vless_installer.modules.trusttunnel import trusttunnel_deeplink_for_user
        # Clear the state file so it looks uninstalled
        self.fx.state_json.unlink()
        link = trusttunnel_deeplink_for_user("alice@example.com", "some-uuid")
        self.assertEqual(link, "")


# =============================================================================
#  TEST 5: Regression — existing protocols unaffected by batching mechanism
# =============================================================================
class TestNoRegressionOnExistingProtocols(unittest.TestCase):
    """Requirement 6: батчинг-механизм и snapshot-до-рестарта не должны
    менять текущее поведение остальных 8 протоколов."""

    def setUp(self):
        _setup_core_in_sysmodules()
        self.tmpdir = Path(tempfile.mkdtemp())
        self.users_json = self.tmpdir / "users.json"
        self.users_json.write_text("[]")
        self.addCleanup(shutil.rmtree, self.tmpdir, ignore_errors=True)

    def test_pending_restarts_empty_for_vless_only_op(self):
        """A VLESS-only add_user should NOT queue any restarts."""
        from vless_installer.modules import user_lifecycle
        user_lifecycle._PENDING_RESTARTS = set()
        user_lifecycle._BATCH_DEPTH = 0

        with patch("vless_installer.modules.user_lifecycle._USERS_FILE", self.users_json), \
             patch.object(user_lifecycle.VlessAdapter, "add", return_value=True), \
             patch.object(user_lifecycle.VlessAdapter, "block", return_value=True):
            result = user_lifecycle.add_user(
                email="test@example.com",
                protocols=["vless"],
                uuid_str="77777777-7777-7777-7777-777777777777",
            )
        self.assertTrue(result["success"])
        # VLESS doesn't call _request_restart, so _PENDING_RESTARTS stays empty
        self.assertEqual(user_lifecycle._PENDING_RESTARTS, set(),
                         "VLESS-only op should not queue any restarts")

    def test_flush_pending_restarts_noop_when_empty(self):
        """_flush_pending_restarts() should be a no-op when the set is empty."""
        from vless_installer.modules import user_lifecycle
        user_lifecycle._PENDING_RESTARTS = set()
        # This should not raise and should not call any subprocess
        with patch("subprocess.run") as mock_run:
            user_lifecycle._flush_pending_restarts()
            mock_run.assert_not_called()

    def test_cancel_pending_restarts_noop_when_no_match(self):
        """_cancel_pending_restarts should be a no-op when the protocols
        don't match what's pending."""
        from vless_installer.modules import user_lifecycle
        user_lifecycle._PENDING_RESTARTS = {"trusttunnel"}
        user_lifecycle._cancel_pending_restarts(["vless", "awg"])
        self.assertEqual(user_lifecycle._PENDING_RESTARTS, {"trusttunnel"},
                         "cancel for unrelated protocols should not affect pending set")

    def test_batch_context_flushes_on_normal_exit(self):
        """batch_context should flush pending restarts on normal exit."""
        from vless_installer.modules import user_lifecycle
        user_lifecycle._PENDING_RESTARTS = set()
        user_lifecycle._BATCH_DEPTH = 0

        flush_called = False
        orig_flush = user_lifecycle._flush_pending_restarts
        def mock_flush():
            nonlocal flush_called
            flush_called = True
            user_lifecycle._PENDING_RESTARTS = set()

        with patch.object(user_lifecycle, "_flush_pending_restarts", side_effect=mock_flush):
            user_lifecycle._PENDING_RESTARTS = {"trusttunnel"}
            with user_lifecycle.batch_context():
                pass  # no-op
        self.assertTrue(flush_called, "batch_context should call _flush_pending_restarts on exit")

    def test_batch_context_does_not_flush_on_exception(self):
        """batch_context should NOT flush on exception (rollback path)."""
        from vless_installer.modules import user_lifecycle
        user_lifecycle._PENDING_RESTARTS = set()
        user_lifecycle._BATCH_DEPTH = 0

        flush_called = False
        def mock_flush():
            nonlocal flush_called
            flush_called = True

        with patch.object(user_lifecycle, "_flush_pending_restarts", side_effect=mock_flush):
            user_lifecycle._PENDING_RESTARTS = {"trusttunnel"}
            with self.assertRaises(RuntimeError):
                with user_lifecycle.batch_context():
                    raise RuntimeError("simulated failure")
        self.assertFalse(flush_called,
                         "batch_context should NOT flush on exception (rollback path)")
        # Pending restarts should be discarded (not flushed)
        self.assertEqual(user_lifecycle._PENDING_RESTARTS, set(),
                         "pending restarts should be discarded on exception")


# =============================================================================
#  TEST: Real credentials.toml format roundtrip
# =============================================================================
class TestRealCredentialsTomlFormat(unittest.TestCase):
    """Verify that our TOML parser/writer handles the REAL format from Phase 0
    (not a made-up format). Uses the actual credentials.toml content that
    was generated by setup_wizard v1.0.33 during the Phase 0 sanity-check."""

    def setUp(self):
        _setup_core_in_sysmodules()

    def test_parse_real_creds_file(self):
        """Parse the real 3-user credentials.toml from Phase 0."""
        from vless_installer.modules.trusttunnel import _parse_credentials_toml
        clients = _parse_credentials_toml(_REAL_CREDS_TOML)
        self.assertEqual(len(clients), 3)
        self.assertEqual(clients[0]["username"], "alice@example.com")
        self.assertEqual(clients[0]["password"], "alice-pass")
        self.assertEqual(clients[1]["username"], "bob@example.com")
        self.assertEqual(clients[1]["password"], "bob-pass")
        self.assertEqual(clients[1]["max_http2_conns"], 16)
        self.assertEqual(clients[2]["username"], "carol@example.com")
        self.assertEqual(clients[2]["max_http3_conns"], 2)

    def test_format_roundtrip_preserves_structure(self):
        """Format → parse → format should be stable."""
        from vless_installer.modules.trusttunnel import (
            _parse_credentials_toml, _format_credentials_toml,
        )
        clients = _parse_credentials_toml(_REAL_CREDS_TOML)
        reformatted = _format_credentials_toml(clients)
        clients2 = _parse_credentials_toml(reformatted)
        self.assertEqual(len(clients2), 3)
        for orig, rt in zip(clients, clients2):
            self.assertEqual(orig["username"], rt["username"])
            self.assertEqual(orig["password"], rt["password"])
        # max_http2_conns and max_http3_conns should survive
        self.assertEqual(clients2[1].get("max_http2_conns"), 16)
        self.assertEqual(clients2[2].get("max_http3_conns"), 2)


# =============================================================================
#  TEST: Real deep-link format roundtrip
# =============================================================================
class TestRealDeeplinkFormat(unittest.TestCase):
    """Verify our pure-Python TLV codec produces/decodes the REAL upstream
    tt://?<base64url> format. Uses a URI actually generated by
    trusttunnel_endpoint v1.0.33 in Phase 0."""

    def setUp(self):
        _setup_core_in_sysmodules()

    def test_decode_real_upstream_deeplink(self):
        """Decode a real tt:// URI generated by the upstream binary."""
        from vless_installer.modules.trusttunnel import trusttunnel_deeplink_decode
        decoded = trusttunnel_deeplink_decode(_REAL_DEEPLINK_ALICE)
        self.assertEqual(decoded["hostname"], "test.example.com")
        self.assertEqual(decoded["username"], "alice")
        self.assertEqual(decoded["password"], "alice-pass")
        self.assertEqual(len(decoded["addresses"]), 1)
        self.assertEqual(decoded["addresses"][0], "203.0.113.10:8443")
        self.assertEqual(decoded["upstream_protocol"], "http2")

    def test_encode_decode_roundtrip(self):
        """Encode → decode should preserve all fields."""
        from vless_installer.modules.trusttunnel import (
            trusttunnel_deeplink_encode, trusttunnel_deeplink_decode,
        )
        uri = trusttunnel_deeplink_encode(
            hostname="vpn.example.com",
            addresses=["vpn.example.com:8443", "203.0.113.5:8443"],
            username="bob@example.com",
            password="secret-pass",
            upstream_protocol="http2",
            name="Bob VPN",
        )
        self.assertTrue(uri.startswith("tt://?"))
        decoded = trusttunnel_deeplink_decode(uri)
        self.assertEqual(decoded["hostname"], "vpn.example.com")
        self.assertEqual(decoded["username"], "bob@example.com")
        self.assertEqual(decoded["password"], "secret-pass")
        self.assertEqual(len(decoded["addresses"]), 2)
        self.assertEqual(decoded["addresses"][0], "vpn.example.com:8443")
        self.assertEqual(decoded["addresses"][1], "203.0.113.5:8443")
        self.assertEqual(decoded["name"], "Bob VPN")
        self.assertEqual(decoded["upstream_protocol"], "http2")


# =============================================================================
#  TEST: Deterministic password (D8)
# =============================================================================
class TestDeterministicPassword(unittest.TestCase):
    """Verify SHA-256("trusttunnel-pass|" + uuid) password derivation (D8)."""

    def setUp(self):
        _setup_core_in_sysmodules()

    def test_password_is_deterministic(self):
        """Same uuid → same password, across calls."""
        import hashlib
        from vless_installer.modules.trusttunnel import trusttunnel_derive_password
        uuid_str = "12345678-1234-1234-1234-123456789abc"
        p1 = trusttunnel_derive_password(uuid_str)
        p2 = trusttunnel_derive_password(uuid_str)
        self.assertEqual(p1, p2)
        # Should be 64-char hex
        self.assertEqual(len(p1), 64)
        self.assertTrue(all(c in "0123456789abcdef" for c in p1))

    def test_password_matches_expected_sha256(self):
        """Verify the exact formula."""
        import hashlib
        from vless_installer.modules.trusttunnel import trusttunnel_derive_password
        uuid_str = "abc-def"
        expected = hashlib.sha256(b"trusttunnel-pass|" + uuid_str.encode()).hexdigest()
        self.assertEqual(trusttunnel_derive_password(uuid_str), expected)

    def test_different_uuids_different_passwords(self):
        from vless_installer.modules.trusttunnel import trusttunnel_derive_password
        p1 = trusttunnel_derive_password("11111111-1111-1111-1111-111111111111")
        p2 = trusttunnel_derive_password("22222222-2222-2222-2222-222222222222")
        self.assertNotEqual(p1, p2)


# =============================================================================
#  TEST: TrustTunnelAdapter registration
# =============================================================================
class TestAdapterRegistration(unittest.TestCase):
    """Verify TrustTunnelAdapter is properly registered in the protocol
    registry."""

    def setUp(self):
        _setup_core_in_sysmodules()

    def test_trusttunnel_in_all_protocols(self):
        from vless_installer.modules import user_lifecycle
        self.assertIn("trusttunnel", user_lifecycle.ALL_PROTOCOLS)

    def test_trusttunnel_in_protocol_adapters(self):
        from vless_installer.modules import user_lifecycle
        self.assertIn("trusttunnel", user_lifecycle.PROTOCOL_ADAPTERS)
        self.assertIs(
            user_lifecycle.PROTOCOL_ADAPTERS["trusttunnel"],
            user_lifecycle.TrustTunnelAdapter,
        )

    def test_adapter_has_required_methods(self):
        from vless_installer.modules import user_lifecycle
        adapter = user_lifecycle.TrustTunnelAdapter
        for method in ("add", "remove", "block", "unblock"):
            self.assertTrue(hasattr(adapter, method),
                            f"TrustTunnelAdapter missing {method}")
            self.assertEqual(adapter.PROTOCOL_NAME, "trusttunnel")

    def test_state_files_includes_trusttunnel(self):
        """_state_files_for_protocols should include credentials.toml + state.json."""
        from vless_installer.modules import user_lifecycle
        files = user_lifecycle._state_files_for_protocols(["trusttunnel"])
        paths_str = [str(f) for f in files]
        # Should include _TRUSTTUNNEL_CREDS_FILE and _TRUSTTUNNEL_STATE_FILE
        self.assertIn(str(user_lifecycle._TRUSTTUNNEL_CREDS_FILE), paths_str)
        self.assertIn(str(user_lifecycle._TRUSTTUNNEL_STATE_FILE), paths_str)


if __name__ == "__main__":
    unittest.main(verbosity=2)
