#!/usr/bin/env python3
"""
tests/test_trusttunnel.py
───────────────────────────────────────────────────────────────────────────────
Unit-тесты для chimera/modules/trusttunnel.py (main module).

Покрывает:
  1. credentials.toml CRUD (parse, format, add, remove, update, list, exists)
  2. Deep-link codec (encode/decode roundtrip, real upstream URI decode)
  3. Deterministic password derivation (D8)
  4. State file load/save
  5. PackageSpec definition (dry_run=True returns False without network)
  6. Mirror URL builder
  7. Port/domain conflict checks (D2, D7)
  8. systemd unit template contains ExecReload (D9)

REAL FORMATS из Phase 0:
  • credentials.toml — реальный TOML [[client]] формат (3-user файл,
    сгенерированный setup_wizard v1.0.33).
  • tt://?<base64url> — реальный upstream TLV deep-link (декодирован
    scripts/deeplink_to_config.py в Phase 0).
  • trusttunnel_endpoint --version → "1.0.33".
  • systemd unit template — реальный trusttunnel.service.template из релиза.
"""
from __future__ import annotations

import json
import os
import shutil
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch, MagicMock

_PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_PROJECT_ROOT))


def _setup_core_in_sysmodules():
    core_path = _PROJECT_ROOT / "chimera" / "_core.py"
    src = core_path.read_text()
    g = {}
    with patch.object(Path, 'mkdir', lambda self, *a, **kw: None), \
         patch.object(Path, 'touch', lambda self, *a, **kw: None), \
         patch.object(Path, 'chmod', lambda self, *a, **kw: None), \
         patch('os.chown', lambda *a, **kw: None), \
         patch('os.geteuid', return_value=0):
        exec(compile(src, str(core_path), "exec"), g)
    import types
    fake_core = types.ModuleType("chimera._core")
    fake_core.__dict__.update(g)
    sys.modules["chimera._core"] = fake_core


# Real credentials.toml content from Phase 0 sanity-check
_REAL_CREDS_3_USERS = """\
[[client]]
username = "alice@example.com"
password = "alice-pass"

[[client]]
username = "bob@example.com"
password = "bob-pass"
max_http2_conns = 16

[[client]]
username = "carol@example.com"
password = "carol-pass"
max_http3_conns = 2
"""

# Real deep-link generated by trusttunnel_endpoint v1.0.33 in Phase 0
_REAL_DEEPLINK = (
    "tt://?AAEBARB0ZXN0LmV4YW1wbGUuY29tBQVhbGljZQYKYWxpY2UtcGFzcwIR"
    "MjAzLjAuMTEzLjEwOjg0NDMIQW8wggFrMIIBEaADAgECAhRudS_h5WQZQSCi"
    "ohxold3qFw-0EjAKBggqhkjOPQQDAjAbMRkwFwYDVQQDDBB0ZXN0LmV4YW1w"
    "bGUuY29tMB4XDTI2MDcxNDAwMDAwMFoXDTI3MDcxNDAwMDAwMFowGzEZMBcG"
    "A1UEAwwQdGVzdC5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEH"
    "A0IABIikkHEVnjGUhyyApK0VAm3Blck2ou42ZAR5mEJCL-nTtWbO-RQwX5MZ"
    "ioag_JgZSMChDqDV3e6grmiT3ozXqSOjMzAxMC8GA1UdEQQoMCaCEHRlc3Qu"
    "ZXhhbXBsZS5jb22CEioudGVzdC5leGFtcGxlLmNvbTAKBggqhkjOPQQDAgNI"
    "ADBFAiEAyR9R0y6ueyDP_jZqAxexSF3E9rtGkBLwcEl0pIqvW1wCIEIhrW65"
    "E4xmp1dfGx1vgI5MZPWHedTBklNLCHcujVD1"
)


# =============================================================================
#  Credentials TOML parser/writer
# =============================================================================
class TestCredentialsTomlParser(unittest.TestCase):

    def setUp(self):
        _setup_core_in_sysmodules()

    def test_parse_real_3_user_file(self):
        from chimera.modules.trusttunnel import _parse_credentials_toml
        clients = _parse_credentials_toml(_REAL_CREDS_3_USERS)
        self.assertEqual(len(clients), 3)
        self.assertEqual(clients[0]["username"], "alice@example.com")
        self.assertEqual(clients[0]["password"], "alice-pass")
        self.assertEqual(clients[1]["max_http2_conns"], 16)
        self.assertEqual(clients[2]["max_http3_conns"], 2)

    def test_parse_empty_file(self):
        from chimera.modules.trusttunnel import _parse_credentials_toml
        self.assertEqual(_parse_credentials_toml(""), [])

    def test_parse_comments_ignored(self):
        from chimera.modules.trusttunnel import _parse_credentials_toml
        text = "# comment\n[[client]]\n# another comment\nusername = \"x\"\npassword = \"y\"\n"
        clients = _parse_credentials_toml(text)
        self.assertEqual(len(clients), 1)
        self.assertEqual(clients[0]["username"], "x")

    def test_format_single_user(self):
        from chimera.modules.trusttunnel import _format_credentials_toml
        out = _format_credentials_toml([{"username": "u", "password": "p"}])
        self.assertIn('[[client]]', out)
        self.assertIn('username = "u"', out)
        self.assertIn('password = "p"', out)

    def test_format_with_conn_limits(self):
        from chimera.modules.trusttunnel import _format_credentials_toml
        out = _format_credentials_toml([{
            "username": "u", "password": "p",
            "max_http2_conns": 32, "max_http3_conns": 4,
        }])
        self.assertIn("max_http2_conns = 32", out)
        self.assertIn("max_http3_conns = 4", out)

    def test_roundtrip_preserves_all_fields(self):
        from chimera.modules.trusttunnel import (
            _parse_credentials_toml, _format_credentials_toml,
        )
        original = _parse_credentials_toml(_REAL_CREDS_3_USERS)
        reformatted = _format_credentials_toml(original)
        reparsed = _parse_credentials_toml(reformatted)
        self.assertEqual(len(reparsed), 3)
        for orig, rt in zip(original, reparsed):
            self.assertEqual(orig, rt)


# =============================================================================
#  Credentials CRUD operations
# =============================================================================
class TestCredentialsCrud(unittest.TestCase):

    def setUp(self):
        _setup_core_in_sysmodules()
        self.tmpdir = Path(tempfile.mkdtemp())
        self.creds = self.tmpdir / "credentials.toml"
        self.state = self.tmpdir / "trusttunnel.json"
        self.binary = self.tmpdir / "trusttunnel_endpoint"
        self.binary.write_text("#!/bin/sh\nexit 0\n")
        self.binary.chmod(0o755)
        self.addCleanup(shutil.rmtree, self.tmpdir, ignore_errors=True)

    def _patches(self):
        return [
            patch("chimera.modules.trusttunnel._CREDS_TOML", self.creds),
            patch("chimera.modules.trusttunnel._STATE_FILE", self.state),
            patch("chimera.modules.trusttunnel._BINARY_PATH", self.binary),
        ]

    def test_list_users_empty_when_no_file(self):
        from chimera.modules.trusttunnel import trusttunnel_list_users
        for p in self._patches():
            p.start()
        try:
            self.assertEqual(trusttunnel_list_users(), [])
        finally:
            patch.stopall()

    def test_list_users_returns_parsed_clients(self):
        from chimera.modules.trusttunnel import trusttunnel_list_users
        self.creds.write_text(_REAL_CREDS_3_USERS)
        for p in self._patches():
            p.start()
        try:
            users = trusttunnel_list_users()
            self.assertEqual(len(users), 3)
        finally:
            patch.stopall()

    def test_user_exists_true_for_existing(self):
        from chimera.modules.trusttunnel import trusttunnel_user_exists
        self.creds.write_text(_REAL_CREDS_3_USERS)
        for p in self._patches():
            p.start()
        try:
            self.assertTrue(trusttunnel_user_exists("alice@example.com"))
            self.assertTrue(trusttunnel_user_exists("bob@example.com"))
            self.assertFalse(trusttunnel_user_exists("eve@example.com"))
            self.assertFalse(trusttunnel_user_exists(""))
        finally:
            patch.stopall()

    def test_add_user_creates_new_entry(self):
        from chimera.modules.trusttunnel import (
            trusttunnel_add_user, trusttunnel_list_users,
        )
        self.creds.write_text("")
        for p in self._patches():
            p.start()
        try:
            ok = trusttunnel_add_user("new@example.com", "secret")
            self.assertTrue(ok)
            users = trusttunnel_list_users()
            self.assertEqual(len(users), 1)
            self.assertEqual(users[0]["username"], "new@example.com")
            self.assertEqual(users[0]["password"], "secret")
        finally:
            patch.stopall()

    def test_add_user_idempotent_no_duplicate(self):
        """D5: calling add twice with same username should update, not duplicate."""
        from chimera.modules.trusttunnel import (
            trusttunnel_add_user, trusttunnel_list_users,
        )
        self.creds.write_text("")
        for p in self._patches():
            p.start()
        try:
            trusttunnel_add_user("dup@example.com", "pass1")
            trusttunnel_add_user("dup@example.com", "pass2")
            users = trusttunnel_list_users()
            self.assertEqual(len(users), 1, "should not create duplicate")
            self.assertEqual(users[0]["password"], "pass2", "should update password")
        finally:
            patch.stopall()

    def test_add_user_with_conn_limits(self):
        from chimera.modules.trusttunnel import (
            trusttunnel_add_user, trusttunnel_list_users,
        )
        self.creds.write_text("")
        for p in self._patches():
            p.start()
        try:
            trusttunnel_add_user("u@e.com", "p", max_http2_conns=8, max_http3_conns=2)
            users = trusttunnel_list_users()
            self.assertEqual(users[0].get("max_http2_conns"), 8)
            self.assertEqual(users[0].get("max_http3_conns"), 2)
        finally:
            patch.stopall()

    def test_remove_user_existing(self):
        from chimera.modules.trusttunnel import (
            trusttunnel_remove_user, trusttunnel_list_users,
        )
        self.creds.write_text(_REAL_CREDS_3_USERS)
        for p in self._patches():
            p.start()
        try:
            ok = trusttunnel_remove_user("bob@example.com")
            self.assertTrue(ok)
            users = trusttunnel_list_users()
            self.assertEqual(len(users), 2)
            usernames = [u["username"] for u in users]
            self.assertNotIn("bob@example.com", usernames)
        finally:
            patch.stopall()

    def test_remove_user_nonexistent_is_noop(self):
        from chimera.modules.trusttunnel import (
            trusttunnel_remove_user, trusttunnel_list_users,
        )
        self.creds.write_text(_REAL_CREDS_3_USERS)
        for p in self._patches():
            p.start()
        try:
            ok = trusttunnel_remove_user("nobody@example.com")
            self.assertTrue(ok, "remove of non-existent user should return True (idempotent)")
            users = trusttunnel_list_users()
            self.assertEqual(len(users), 3, "file should be unchanged")
        finally:
            patch.stopall()

    def test_update_user_existing(self):
        from chimera.modules.trusttunnel import (
            trusttunnel_update_user, trusttunnel_list_users,
        )
        self.creds.write_text(_REAL_CREDS_3_USERS)
        for p in self._patches():
            p.start()
        try:
            ok = trusttunnel_update_user("alice@example.com", password="new-pass")
            self.assertTrue(ok)
            users = trusttunnel_list_users()
            alice = next(u for u in users if u["username"] == "alice@example.com")
            self.assertEqual(alice["password"], "new-pass")
        finally:
            patch.stopall()

    def test_update_user_nonexistent_returns_false(self):
        from chimera.modules.trusttunnel import trusttunnel_update_user
        self.creds.write_text(_REAL_CREDS_3_USERS)
        for p in self._patches():
            p.start()
        try:
            ok = trusttunnel_update_user("nobody@example.com", password="x")
            self.assertFalse(ok)
        finally:
            patch.stopall()


# =============================================================================
#  Deep-link codec
# =============================================================================
class TestDeeplinkCodec(unittest.TestCase):

    def setUp(self):
        _setup_core_in_sysmodules()

    def test_varint_encode_small(self):
        """Values < 64 encode to single byte."""
        from chimera.modules.trusttunnel import _varint_encode
        self.assertEqual(_varint_encode(0), b"\x00")
        self.assertEqual(_varint_encode(63), b"\x3f")

    def test_varint_encode_medium(self):
        """Values 64-16383 encode to 2 bytes with prefix 01."""
        from chimera.modules.trusttunnel import _varint_encode
        b = _varint_encode(64)
        self.assertEqual(len(b), 2)
        self.assertEqual(b[0] & 0xC0, 0x40)

    def test_varint_decode_roundtrip(self):
        from chimera.modules.trusttunnel import _varint_encode, _varint_decode
        for val in [0, 1, 63, 64, 16383, 16384, 1073741823]:
            encoded = _varint_encode(val)
            decoded, offset = _varint_decode(encoded, 0)
            self.assertEqual(decoded, val, f"roundtrip failed for {val}")
            self.assertEqual(offset, len(encoded))

    def test_decode_real_upstream_deeplink(self):
        """Decode the REAL tt:// URI from Phase 0 sanity-check."""
        from chimera.modules.trusttunnel import trusttunnel_deeplink_decode
        d = trusttunnel_deeplink_decode(_REAL_DEEPLINK)
        self.assertEqual(d["hostname"], "test.example.com")
        self.assertEqual(d["username"], "alice")
        self.assertEqual(d["password"], "alice-pass")
        self.assertEqual(d["addresses"], ["203.0.113.10:8443"])
        self.assertEqual(d["upstream_protocol"], "http2")

    def test_encode_produes_tt_scheme(self):
        from chimera.modules.trusttunnel import trusttunnel_deeplink_encode
        uri = trusttunnel_deeplink_encode(
            hostname="h.com", addresses=["h.com:443"],
            username="u", password="p",
        )
        self.assertTrue(uri.startswith("tt://?"))

    def test_encode_decode_roundtrip_all_fields(self):
        from chimera.modules.trusttunnel import (
            trusttunnel_deeplink_encode, trusttunnel_deeplink_decode,
        )
        uri = trusttunnel_deeplink_encode(
            hostname="vpn.example.com",
            addresses=["1.2.3.4:8443", "vpn.example.com:8443"],
            username="user@test",
            password="p@ss:w0rd",  # password with special chars
            custom_sni="sni.example.com",
            has_ipv6=False,
            skip_verification=True,
            upstream_protocol="http3",
            anti_dpi=True,
            name="My VPN",
            dns_upstreams=["8.8.8.8", "1.1.1.1"],
        )
        d = trusttunnel_deeplink_decode(uri)
        self.assertEqual(d["hostname"], "vpn.example.com")
        self.assertEqual(d["username"], "user@test")
        self.assertEqual(d["password"], "p@ss:w0rd")
        self.assertEqual(len(d["addresses"]), 2)
        self.assertEqual(d["custom_sni"], "sni.example.com")
        self.assertEqual(d["has_ipv6"], False)
        self.assertEqual(d["skip_verification"], True)
        self.assertEqual(d["upstream_protocol"], "http3")
        self.assertEqual(d["anti_dpi"], True)
        self.assertEqual(d["name"], "My VPN")
        self.assertEqual(d["dns_upstreams"], ["8.8.8.8", "1.1.1.1"])

    def test_decode_rejects_non_tt_uri(self):
        from chimera.modules.trusttunnel import trusttunnel_deeplink_decode
        with self.assertRaises(ValueError):
            trusttunnel_deeplink_decode("https://example.com/foo")

    def test_decode_accepts_old_tt_prefix(self):
        """v1.0.12 backward compat: tt://<payload> (without ?) is also accepted."""
        from chimera.modules.trusttunnel import (
            trusttunnel_deeplink_decode, trusttunnel_deeplink_encode,
        )
        uri_new = trusttunnel_deeplink_encode(
            hostname="h.com", addresses=["h.com:443"],
            username="u", password="p",
        )
        # Strip the "?" to simulate old format
        uri_old = uri_new.replace("tt://?", "tt://", 1)
        d = trusttunnel_deeplink_decode(uri_old)
        self.assertEqual(d["hostname"], "h.com")
        self.assertEqual(d["username"], "u")


# =============================================================================
#  Deterministic password (D8)
# =============================================================================
class TestDeterministicPassword(unittest.TestCase):

    def setUp(self):
        _setup_core_in_sysmodules()

    def test_password_is_64_char_hex(self):
        from chimera.modules.trusttunnel import trusttunnel_derive_password
        p = trusttunnel_derive_password("some-uuid")
        self.assertEqual(len(p), 64)
        self.assertTrue(all(c in "0123456789abcdef" for c in p))

    def test_password_deterministic(self):
        from chimera.modules.trusttunnel import trusttunnel_derive_password
        self.assertEqual(
            trusttunnel_derive_password("abc"),
            trusttunnel_derive_password("abc"),
        )

    def test_password_matches_sha256_formula(self):
        import hashlib
        from chimera.modules.trusttunnel import trusttunnel_derive_password
        uuid_str = "test-uuid-123"
        expected = hashlib.sha256(b"trusttunnel-pass|" + uuid_str.encode()).hexdigest()
        self.assertEqual(trusttunnel_derive_password(uuid_str), expected)

    def test_password_raises_on_empty_uuid(self):
        from chimera.modules.trusttunnel import trusttunnel_derive_password
        with self.assertRaises(ValueError):
            trusttunnel_derive_password("")


# =============================================================================
#  State file
# =============================================================================
class TestStateFile(unittest.TestCase):

    def setUp(self):
        _setup_core_in_sysmodules()
        self.tmpdir = Path(tempfile.mkdtemp())
        self.state = self.tmpdir / "trusttunnel.json"
        self.addCleanup(shutil.rmtree, self.tmpdir, ignore_errors=True)

    def test_load_state_empty_when_no_file(self):
        from chimera.modules.trusttunnel import trusttunnel_load_state
        with patch("chimera.modules.trusttunnel._STATE_FILE", self.state):
            self.assertEqual(trusttunnel_load_state(), {})

    def test_save_then_load_roundtrip(self):
        from chimera.modules.trusttunnel import (
            trusttunnel_load_state, trusttunnel_save_state,
        )
        with patch("chimera.modules.trusttunnel._STATE_FILE", self.state):
            state = {
                "installed": True,
                "version": "1.0.33",
                "domain": "tt.example.com",
                "listen_port": 8443,
            }
            trusttunnel_save_state(state)
            loaded = trusttunnel_load_state()
            self.assertEqual(loaded, state)

    def test_is_installed_requires_state_and_binary(self):
        from chimera.modules.trusttunnel import trusttunnel_is_installed
        binary = self.tmpdir / "trusttunnel_endpoint"
        binary.write_text("#!/bin/sh\nexit 0\n")
        with patch("chimera.modules.trusttunnel._STATE_FILE", self.state), \
             patch("chimera.modules.trusttunnel._BINARY_PATH", binary):
            # Not installed — state file missing
            self.assertFalse(trusttunnel_is_installed())
            # Write state
            self.state.write_text(json.dumps({"installed": True, "version": "1.0.33"}))
            self.assertTrue(trusttunnel_is_installed())


# =============================================================================
#  PackageSpec
# =============================================================================
class TestPackageSpec(unittest.TestCase):

    def setUp(self):
        _setup_core_in_sysmodules()

    def test_spec_exists(self):
        from chimera.modules.trusttunnel_packages import TRUSTTUNNEL_SPEC
        self.assertEqual(TRUSTTUNNEL_SPEC.name, "trusttunnel prebuilt binaries")
        self.assertTrue(len(TRUSTTUNNEL_SPEC.install_dests) >= 1)
        self.assertEqual(TRUSTTUNNEL_SPEC.manual_incoming_dir, Path("/root"))

    def test_spec_post_install_is_callable(self):
        from chimera.modules.trusttunnel_packages import TRUSTTUNNEL_SPEC
        self.assertTrue(callable(TRUSTTUNNEL_SPEC.post_install))

    def test_filename_builder_produces_correct_name(self):
        from chimera.modules.trusttunnel_packages import _build_filename
        with patch("platform.machine", return_value="x86_64"):
            name = _build_filename(tag="v1.0.33")
            self.assertEqual(name, "trusttunnel-v1.0.33-linux-x86_64.tar.gz")
        with patch("platform.machine", return_value="aarch64"):
            name = _build_filename(tag="v1.0.33")
            self.assertEqual(name, "trusttunnel-v1.0.33-linux-aarch64.tar.gz")

    def test_dry_run_returns_false(self):
        """fetch_package(dry_run=True) should return False without network."""
        from chimera.modules.download_manager import fetch_package
        from chimera.modules.trusttunnel_packages import TRUSTTUNNEL_SPEC
        ok = fetch_package(TRUSTTUNNEL_SPEC, tag="v1.0.33", dry_run=True,
                           print_hint_on_failure=False)
        self.assertFalse(ok, "dry_run should return False")

    def test_mirror_urls_builder(self):
        from chimera.modules.trusttunnel_mirrors import get_trusttunnel_mirrors
        urls = get_trusttunnel_mirrors(tag="v1.0.33",
                                        filename="trusttunnel-v1.0.33-linux-x86_64.tar.gz")
        self.assertEqual(len(urls), 1)
        self.assertIn("github.com/TrustTunnel/TrustTunnel/releases/download/v1.0.33/", urls[0])
        self.assertIn("trusttunnel-v1.0.33-linux-x86_64.tar.gz", urls[0])


# =============================================================================
#  systemd unit template (D9: must contain ExecReload)
# =============================================================================
class TestSystemdUnitTemplate(unittest.TestCase):

    def setUp(self):
        _setup_core_in_sysmodules()

    def test_template_contains_exec_reload(self):
        """D9: the unit template MUST include ExecReload for SIGHUP-based
        cert renewal (no restart = no active session disconnect)."""
        from chimera.modules.trusttunnel import _SYSTEMD_UNIT_TEMPLATE
        self.assertIn("ExecReload=/bin/kill -HUP $MAINPID", _SYSTEMD_UNIT_TEMPLATE)

    def test_template_contains_restart_on_failure(self):
        from chimera.modules.trusttunnel import _SYSTEMD_UNIT_TEMPLATE
        self.assertIn("Restart=on-failure", _SYSTEMD_UNIT_TEMPLATE)

    def test_template_uses_correct_binary_path(self):
        from chimera.modules.trusttunnel import _SYSTEMD_UNIT_TEMPLATE, _BINARY_PATH
        # The template uses {binary} placeholder, format with the actual path
        formatted = _SYSTEMD_UNIT_TEMPLATE.format(
            install_dir=Path("/opt/trusttunnel"),
            binary=_BINARY_PATH,
        )
        self.assertIn(str(_BINARY_PATH), formatted)
        self.assertIn("vpn.toml hosts.toml", formatted)


# =============================================================================
#  Port and domain conflict checks (D2, D7)
# =============================================================================
class TestPortDomainConflictChecks(unittest.TestCase):

    def setUp(self):
        _setup_core_in_sysmodules()
        self.tmpdir = Path(tempfile.mkdtemp())
        self.addCleanup(shutil.rmtree, self.tmpdir, ignore_errors=True)

    def test_check_port_available_calls_core(self):
        """_check_port_available should delegate to core.check_port_used_by_other_protocol."""
        from chimera.modules import trusttunnel
        with patch.object(trusttunnel._core_module(),
                          "check_port_used_by_other_protocol",
                          return_value="port 443 taken by VLESS") as mock_check:
            result = trusttunnel._check_port_available(8443)
            self.assertIn("443", result)
            mock_check.assert_called_once_with(8443, exclude_module="trusttunnel")

    def test_check_domain_available_detects_vless_collision(self):
        """D7: domain collision with VLESS PARAM_DOMAIN should be detected."""
        from chimera.modules import trusttunnel
        # Mock the core module to have PARAM_DOMAIN = "vless.example.com"
        with patch.object(trusttunnel._core_module(), "PARAM_DOMAIN",
                          "vless.example.com"):
            result = trusttunnel._check_domain_available("vless.example.com")
            self.assertNotEqual(result, "")
            self.assertIn("VLESS", result)

    def test_check_domain_available_passes_for_unused_domain(self):
        from chimera.modules import trusttunnel
        with patch.object(trusttunnel._core_module(), "PARAM_DOMAIN",
                          "vless.example.com"):
            result = trusttunnel._check_domain_available("new-tt.example.com")
            self.assertEqual(result, "")

    def test_check_domain_available_rejects_empty(self):
        from chimera.modules import trusttunnel
        result = trusttunnel._check_domain_available("")
        self.assertNotEqual(result, "")


# =============================================================================
#  TrustTunnel service control (mocked)
# =============================================================================
class TestServiceControl(unittest.TestCase):

    def setUp(self):
        _setup_core_in_sysmodules()

    def test_restart_service_calls_systemctl(self):
        from chimera.modules import trusttunnel
        with patch("subprocess.run", return_value=MagicMock(returncode=0)) as mock_run:
            ok = trusttunnel.trusttunnel_restart_service()
            self.assertTrue(ok)
            mock_run.assert_called_once()
            args = mock_run.call_args[0][0]
            self.assertEqual(args[:3], ["systemctl", "restart", "trusttunnel"])

    def test_restart_service_returns_false_on_failure(self):
        from chimera.modules import trusttunnel
        with patch("subprocess.run", return_value=MagicMock(returncode=1, stderr="error")):
            ok = trusttunnel.trusttunnel_restart_service()
            self.assertFalse(ok)

    def test_reload_service_calls_systemctl_reload(self):
        from chimera.modules import trusttunnel
        with patch("subprocess.run", return_value=MagicMock(returncode=0)) as mock_run:
            ok = trusttunnel.trusttunnel_reload_service()
            self.assertTrue(ok)
            args = mock_run.call_args[0][0]
            self.assertEqual(args[:3], ["systemctl", "reload", "trusttunnel"])

    def test_service_active_returns_true_when_is_active_succeeds(self):
        from chimera.modules import trusttunnel
        with patch("subprocess.run", return_value=MagicMock(returncode=0)):
            self.assertTrue(trusttunnel.trusttunnel_service_active())


# =============================================================================
#  Generate deeplink (non-existent user protection)
# =============================================================================
class TestGenerateDeeplink(unittest.TestCase):

    def setUp(self):
        _setup_core_in_sysmodules()
        self.tmpdir = Path(tempfile.mkdtemp())
        self.creds = self.tmpdir / "credentials.toml"
        self.state = self.tmpdir / "trusttunnel.json"
        self.binary = self.tmpdir / "trusttunnel_endpoint"
        self.binary.write_text("#!/bin/sh\nexit 0\n")
        self.binary.chmod(0o755)
        self.creds.write_text(_REAL_CREDS_3_USERS)
        self.state.write_text(json.dumps({
            "installed": True,
            "version": "1.0.33",
            "domain": "tt.example.com",
            "listen_port": 8443,
        }))
        self.addCleanup(shutil.rmtree, self.tmpdir, ignore_errors=True)

    def _patches(self):
        return [
            patch("chimera.modules.trusttunnel._CREDS_TOML", self.creds),
            patch("chimera.modules.trusttunnel._STATE_FILE", self.state),
            patch("chimera.modules.trusttunnel._BINARY_PATH", self.binary),
        ]

    def test_generate_deeplink_nonexistent_user_raises(self):
        """D4: non-existent user → ValueError BEFORE binary invocation."""
        from chimera.modules.trusttunnel import trusttunnel_generate_deeplink
        for p in self._patches():
            p.start()
        try:
            with self.assertRaises(ValueError) as ctx:
                trusttunnel_generate_deeplink("eve@example.com")
            self.assertIn("eve@example.com", str(ctx.exception))
            self.assertIn("not found", str(ctx.exception).lower())
        finally:
            patch.stopall()

    def test_generate_deeplink_existing_user_calls_binary(self):
        from chimera.modules.trusttunnel import trusttunnel_generate_deeplink
        for p in self._patches():
            p.start()
        try:
            mock_result = MagicMock(returncode=0,
                                    stdout="tt://?abc\n\nTo connect...\n",
                                    stderr="")
            with patch("subprocess.run", return_value=mock_result) as mock_run:
                link = trusttunnel_generate_deeplink("alice@example.com")
            self.assertTrue(link.startswith("tt://"))
            mock_run.assert_called_once()
        finally:
            patch.stopall()

    def test_generate_deeplink_not_installed_raises(self):
        from chimera.modules.trusttunnel import trusttunnel_generate_deeplink
        # Overwrite state to mark as not installed
        self.state.write_text(json.dumps({"installed": False}))
        for p in self._patches():
            p.start()
        try:
            with self.assertRaises(RuntimeError):
                trusttunnel_generate_deeplink("alice@example.com")
        finally:
            patch.stopall()


# =============================================================================
#  deeplink_for_user (pure Python, for linkqr_lib)
# =============================================================================
class TestDeeplinkForUser(unittest.TestCase):

    def setUp(self):
        _setup_core_in_sysmodules()
        self.tmpdir = Path(tempfile.mkdtemp())
        self.creds = self.tmpdir / "credentials.toml"
        self.state = self.tmpdir / "trusttunnel.json"
        self.binary = self.tmpdir / "trusttunnel_endpoint"
        self.binary.write_text("#!/bin/sh\nexit 0\n")
        self.creds.write_text(_REAL_CREDS_3_USERS)
        self.state.write_text(json.dumps({
            "installed": True,
            "version": "1.0.33",
            "domain": "tt.example.com",
            "listen_port": 8443,
        }))
        self.addCleanup(shutil.rmtree, self.tmpdir, ignore_errors=True)

    def _patches(self):
        return [
            patch("chimera.modules.trusttunnel._CREDS_TOML", self.creds),
            patch("chimera.modules.trusttunnel._STATE_FILE", self.state),
            patch("chimera.modules.trusttunnel._BINARY_PATH", self.binary),
        ]

    def test_returns_valid_tt_uri_for_existing_user(self):
        from chimera.modules.trusttunnel import trusttunnel_deeplink_for_user
        for p in self._patches():
            p.start()
        try:
            import hashlib
            uuid_str = "test-uuid-abc"
            expected_pass = hashlib.sha256(b"trusttunnel-pass|" + uuid_str.encode()).hexdigest()
            link = trusttunnel_deeplink_for_user("alice@example.com", uuid_str)
            self.assertTrue(link.startswith("tt://?"))
            # Decode and verify
            from chimera.modules.trusttunnel import trusttunnel_deeplink_decode
            d = trusttunnel_deeplink_decode(link)
            self.assertEqual(d["username"], "alice@example.com")
            self.assertEqual(d["password"], expected_pass)
            self.assertEqual(d["hostname"], "tt.example.com")
            self.assertEqual(d["addresses"], ["tt.example.com:8443"])
        finally:
            patch.stopall()

    def test_returns_empty_for_nonexistent_user(self):
        from chimera.modules.trusttunnel import trusttunnel_deeplink_for_user
        for p in self._patches():
            p.start()
        try:
            link = trusttunnel_deeplink_for_user("eve@example.com", "some-uuid")
            self.assertEqual(link, "")
        finally:
            patch.stopall()

    def test_returns_empty_when_not_installed(self):
        from chimera.modules.trusttunnel import trusttunnel_deeplink_for_user
        self.state.write_text(json.dumps({"installed": False}))
        for p in self._patches():
            p.start()
        try:
            link = trusttunnel_deeplink_for_user("alice@example.com", "uuid")
            self.assertEqual(link, "")
        finally:
            patch.stopall()


# =============================================================================
#  Cron install/uninstall (auto-installed on install, removed on uninstall)
# =============================================================================
class TestCronInstallUninstall(unittest.TestCase):
    """Verify that cron jobs are installed during install() and removed
    during uninstall(). Tests use tempdir paths for _CRON_FILE and _SCRIPT_FILE
    so no real /etc/cron.d is touched."""

    def setUp(self):
        _setup_core_in_sysmodules()
        self.tmpdir = Path(tempfile.mkdtemp())
        self.cron_file = self.tmpdir / "cron.d" / "trusttunnel"
        self.script_file = self.tmpdir / "trusttunnel_cron.sh"
        self.fake_main_py = self.tmpdir / "main.py"
        self.fake_main_py.write_text("#!/usr/bin/env python3\nprint('mock')\n")
        self.addCleanup(shutil.rmtree, self.tmpdir, ignore_errors=True)

    def _patches(self):
        return [
            patch("chimera.modules.trusttunnel._CRON_FILE", self.cron_file),
            patch("chimera.modules.trusttunnel._SCRIPT_FILE", self.script_file),
            patch("chimera.modules.trusttunnel._PROJECT_ROOT", self.tmpdir),
        ]

    def test_install_cron_creates_both_files(self):
        """_install_cron() should create both the cron file and the wrapper script."""
        from chimera.modules.trusttunnel import _install_cron, _CRON_INTERVAL_MIN
        for p in self._patches():
            p.start()
        try:
            self.assertFalse(self.cron_file.exists())
            self.assertFalse(self.script_file.exists())
            _install_cron()
            self.assertTrue(self.cron_file.exists(), "cron file should be created")
            self.assertTrue(self.script_file.exists(), "wrapper script should be created")
        finally:
            patch.stopall()

    def test_cron_file_contains_expected_content(self):
        """The cron file should contain both --trusttunnel-health and
        --trusttunnel-stats entries with the correct interval."""
        from chimera.modules.trusttunnel import (
            _install_cron, _CRON_INTERVAL_MIN,
        )
        for p in self._patches():
            p.start()
        try:
            _install_cron()
            cron_text = self.cron_file.read_text()
            # Should contain both health and stats entries
            self.assertIn("health", cron_text)
            self.assertIn("stats", cron_text)
            # Should contain the interval (e.g. */5)
            self.assertIn(f"*/{_CRON_INTERVAL_MIN}", cron_text)
            # Should reference the wrapper script
            self.assertIn(str(self.script_file), cron_text)
            # Should run as root
            self.assertIn("root", cron_text)
        finally:
            patch.stopall()

    def test_script_file_contains_main_py_reference(self):
        """The wrapper script should reference main.py and both CLI flags."""
        from chimera.modules.trusttunnel import _install_cron
        for p in self._patches():
            p.start()
        try:
            _install_cron()
            script_text = self.script_file.read_text()
            self.assertIn("--trusttunnel-health", script_text)
            self.assertIn("--trusttunnel-stats", script_text)
            self.assertIn("main.py", script_text)
            self.assertIn("#!/bin/bash", script_text)
        finally:
            patch.stopall()

    def test_script_file_is_executable(self):
        """The wrapper script should be chmod 0o755."""
        from chimera.modules.trusttunnel import _install_cron
        for p in self._patches():
            p.start()
        try:
            _install_cron()
            mode = self.script_file.stat().st_mode & 0o777
            self.assertEqual(mode, 0o755, f"script should be 0o755, got {oct(mode)}")
        finally:
            patch.stopall()

    def test_install_cron_is_idempotent(self):
        """Calling _install_cron() twice should not error — overwrites."""
        from chimera.modules.trusttunnel import _install_cron
        for p in self._patches():
            p.start()
        try:
            _install_cron()
            _install_cron()  # should not raise
            self.assertTrue(self.cron_file.exists())
        finally:
            patch.stopall()

    def test_remove_cron_deletes_both_files(self):
        """_remove_cron() should delete both the cron file and the wrapper script."""
        from chimera.modules.trusttunnel import _install_cron, _remove_cron
        for p in self._patches():
            p.start()
        try:
            _install_cron()
            self.assertTrue(self.cron_file.exists())
            self.assertTrue(self.script_file.exists())
            _remove_cron()
            self.assertFalse(self.cron_file.exists(), "cron file should be removed")
            self.assertFalse(self.script_file.exists(), "script should be removed")
        finally:
            patch.stopall()

    def test_remove_cron_idempotent_when_not_installed(self):
        """_remove_cron() should not error if files don't exist."""
        from chimera.modules.trusttunnel import _remove_cron
        for p in self._patches():
            p.start()
        try:
            # Should not raise even though files don't exist
            _remove_cron()
            self.assertFalse(self.cron_file.exists())
        finally:
            patch.stopall()

    def test_cron_installed_check(self):
        """trusttunnel_cron_installed() should return True after install, False after remove."""
        from chimera.modules.trusttunnel import (
            _install_cron, _remove_cron, trusttunnel_cron_installed,
        )
        for p in self._patches():
            p.start()
        try:
            self.assertFalse(trusttunnel_cron_installed())
            _install_cron()
            self.assertTrue(trusttunnel_cron_installed())
            _remove_cron()
            self.assertFalse(trusttunnel_cron_installed())
        finally:
            patch.stopall()

    def test_install_then_uninstall_full_cycle_cron(self):
        """Integration: trusttunnel_install() should call _install_cron(),
        and trusttunnel_uninstall() should call _remove_cron(). This mocks
        ALL the heavy install steps + the cron functions themselves, and
        verifies the call wiring (not the file creation — that's covered by
        the unit tests above)."""
        from chimera.modules import trusttunnel
        install_cron_called = []
        remove_cron_called = []

        def mock_install_cron():
            install_cron_called.append(True)

        def mock_remove_cron():
            remove_cron_called.append(True)

        # Patch the cron functions to track calls, and patch all heavy
        # install/uninstall steps to no-op. We also need to make
        # trusttunnel_install return True, which requires patching the
        # download + cert + setup_wizard chain.
        patches = [
            patch.object(trusttunnel, "_install_cron", side_effect=mock_install_cron),
            patch.object(trusttunnel, "_remove_cron", side_effect=mock_remove_cron),
            patch.object(trusttunnel, "_download_and_install_binary",
                         return_value=(True, "1.0.33")),
            patch.object(trusttunnel, "_import_gpg_key"),
            patch.object(trusttunnel, "_verify_gpg_signature", return_value=True),
            patch("chimera.modules.ssl_certbot.obtain_ssl_cert"),
            patch.object(trusttunnel, "_check_domain_available", return_value=""),
            patch.object(trusttunnel, "_check_port_available", return_value=""),
            patch.object(trusttunnel, "_open_port"),
            patch.object(trusttunnel, "_close_port"),
            patch.object(trusttunnel, "_install_systemd_unit"),
            patch.object(trusttunnel, "_remove_systemd_unit"),
            patch.object(trusttunnel, "_install_cert_renewal_hook"),
            patch.object(trusttunnel, "_remove_cert_renewal_hook"),
            patch("subprocess.run", return_value=MagicMock(returncode=0)),
            patch.object(trusttunnel, "_INSTALL_DIR", self.tmpdir / "tt"),
            patch.object(trusttunnel, "_BINARY_PATH", self.tmpdir / "tt" / "endpoint"),
            patch.object(trusttunnel, "_WIZARD_PATH", self.tmpdir / "tt" / "wizard"),
            patch.object(trusttunnel, "_VPN_TOML", self.tmpdir / "tt" / "vpn.toml"),
            patch.object(trusttunnel, "_HOSTS_TOML", self.tmpdir / "tt" / "hosts.toml"),
            patch.object(trusttunnel, "_CREDS_TOML", self.tmpdir / "tt" / "creds.toml"),
            patch.object(trusttunnel, "_RULES_TOML", self.tmpdir / "tt" / "rules.toml"),
            patch.object(trusttunnel, "_STATE_FILE", self.tmpdir / "state.json"),
            patch("pathlib.Path.exists", return_value=True),
            patch.object(trusttunnel, "_STATE_FILE",
                         self.tmpdir / "state.json"),
            patch.object(trusttunnel, "trusttunnel_load_state",
                         return_value={"installed": True, "listen_port": 8443}),
        ]
        for p in patches:
            p.start()
        try:
            # Install should call _install_cron
            ok = trusttunnel.trusttunnel_install("test.example.com", 8443, "")
            self.assertTrue(ok, "install should succeed")
            self.assertEqual(len(install_cron_called), 1,
                             "_install_cron should be called once during install")

            # Uninstall should call _remove_cron
            ok = trusttunnel.trusttunnel_uninstall()
            self.assertTrue(ok, "uninstall should succeed")
            self.assertEqual(len(remove_cron_called), 1,
                             "_remove_cron should be called once during uninstall")
        finally:
            patch.stopall()


if __name__ == "__main__":
    unittest.main(verbosity=2)
